package com.wisedrive.obd2.constants

/**
 * DTC Info holder
 */
data class DTCInfo(val description: String, val severity: String)

/**
 * DTC Descriptions - Part 1: Powertrain P0xxx codes
 * Complete database of 4000+ OBD-II diagnostic trouble codes
 */
object DTCDescriptionsP0 {
    
    val P0_CODES: Map<String, DTCInfo> = mapOf(
        // P00xx - Fuel and Air Metering
        "P0001" to DTCInfo("Fuel Volume Regulator Control Circuit/Open", "Critical"),
        "P0002" to DTCInfo("Fuel Volume Regulator Control Circuit Range/Performance", "Critical"),
        "P0003" to DTCInfo("Fuel Volume Regulator Control Circuit Low", "Critical"),
        "P0004" to DTCInfo("Fuel Volume Regulator Control Circuit High", "Critical"),
        "P0005" to DTCInfo("Fuel Shutoff Valve A Control Circuit/Open", "Critical"),
        "P0006" to DTCInfo("Fuel Shutoff Valve A Control Circuit Low", "Critical"),
        "P0007" to DTCInfo("Fuel Shutoff Valve A Control Circuit High", "Critical"),
        "P0008" to DTCInfo("Engine Position System Performance Bank 1", "Critical"),
        "P0009" to DTCInfo("Engine Position System Performance Bank 2", "Critical"),
        "P0010" to DTCInfo("A Camshaft Position Actuator Circuit (Bank 1)", "Important"),
        "P0011" to DTCInfo("A Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)", "Important"),
        "P0012" to DTCInfo("A Camshaft Position - Timing Over-Retarded (Bank 1)", "Important"),
        "P0013" to DTCInfo("B Camshaft Position - Actuator Circuit (Bank 1)", "Important"),
        "P0014" to DTCInfo("B Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)", "Important"),
        "P0015" to DTCInfo("B Camshaft Position - Timing Over-Retarded (Bank 1)", "Important"),
        "P0016" to DTCInfo("Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)", "Critical"),
        "P0017" to DTCInfo("Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)", "Critical"),
        "P0018" to DTCInfo("Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)", "Critical"),
        "P0019" to DTCInfo("Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)", "Critical"),
        "P0020" to DTCInfo("A Camshaft Position Actuator Circuit (Bank 2)", "Important"),
        "P0021" to DTCInfo("A Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)", "Important"),
        "P0022" to DTCInfo("A Camshaft Position - Timing Over-Retarded (Bank 2)", "Important"),
        "P0023" to DTCInfo("B Camshaft Position - Actuator Circuit (Bank 2)", "Important"),
        "P0024" to DTCInfo("B Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)", "Important"),
        "P0025" to DTCInfo("B Camshaft Position - Timing Over-Retarded (Bank 2)", "Important"),
        "P0026" to DTCInfo("Intake Valve Control Solenoid Circuit Range/Performance (Bank 1)", "Important"),
        "P0027" to DTCInfo("Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 1)", "Important"),
        "P0028" to DTCInfo("Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)", "Important"),
        "P0029" to DTCInfo("Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)", "Important"),
        "P0030" to DTCInfo("HO2S Heater Control Circuit (Bank 1 Sensor 1)", "Important"),
        "P0031" to DTCInfo("HO2S Heater Control Circuit Low (Bank 1 Sensor 1)", "Important"),
        "P0032" to DTCInfo("HO2S Heater Control Circuit High (Bank 1 Sensor 1)", "Important"),
        "P0033" to DTCInfo("Turbo Charger Bypass Valve Control Circuit", "Important"),
        "P0034" to DTCInfo("Turbo Charger Bypass Valve Control Circuit Low", "Important"),
        "P0035" to DTCInfo("Turbo Charger Bypass Valve Control Circuit High", "Important"),
        "P0036" to DTCInfo("HO2S Heater Control Circuit (Bank 1 Sensor 2)", "Important"),
        "P0037" to DTCInfo("HO2S Heater Control Circuit Low (Bank 1 Sensor 2)", "Important"),
        "P0038" to DTCInfo("HO2S Heater Control Circuit High (Bank 1 Sensor 2)", "Important"),
        "P0039" to DTCInfo("Turbo/Super Charger Bypass Valve Control Circuit Range/Performance", "Important"),
        "P0040" to DTCInfo("O2 Sensor Signals Swapped Bank 1 Sensor 1/ Bank 2 Sensor 1", "Important"),
        "P0041" to DTCInfo("O2 Sensor Signals Swapped Bank 1 Sensor 2/ Bank 2 Sensor 2", "Important"),
        "P0042" to DTCInfo("HO2S Heater Control Circuit (Bank 1 Sensor 3)", "Non-Critical"),
        "P0043" to DTCInfo("HO2S Heater Control Circuit Low (Bank 1 Sensor 3)", "Non-Critical"),
        "P0044" to DTCInfo("HO2S Heater Control Circuit High (Bank 1 Sensor 3)", "Non-Critical"),
        "P0045" to DTCInfo("Turbo/Super Charger Boost Control Solenoid Circuit/Open", "Important"),
        "P0046" to DTCInfo("Turbo/Super Charger Boost Control Solenoid Circuit Range/Performance", "Important"),
        "P0047" to DTCInfo("Turbo/Super Charger Boost Control Solenoid Circuit Low", "Important"),
        "P0048" to DTCInfo("Turbo/Super Charger Boost Control Solenoid Circuit High", "Important"),
        "P0049" to DTCInfo("Turbo/Super Charger Turbine Overspeed", "Critical"),
        "P0050" to DTCInfo("HO2S Heater Control Circuit (Bank 2 Sensor 1)", "Important"),
        "P0051" to DTCInfo("HO2S Heater Control Circuit Low (Bank 2 Sensor 1)", "Important"),
        "P0052" to DTCInfo("HO2S Heater Control Circuit High (Bank 2 Sensor 1)", "Important"),
        "P0053" to DTCInfo("HO2S Heater Resistance (Bank 1 Sensor 1)", "Non-Critical"),
        "P0054" to DTCInfo("HO2S Heater Resistance (Bank 1 Sensor 2)", "Non-Critical"),
        "P0055" to DTCInfo("HO2S Heater Resistance (Bank 1 Sensor 3)", "Non-Critical"),
        "P0056" to DTCInfo("HO2S Heater Control Circuit (Bank 2 Sensor 2)", "Important"),
        "P0057" to DTCInfo("HO2S Heater Control Circuit Low (Bank 2 Sensor 2)", "Important"),
        "P0058" to DTCInfo("HO2S Heater Control Circuit High (Bank 2 Sensor 2)", "Important"),
        "P0059" to DTCInfo("HO2S Heater Resistance (Bank 2 Sensor 1)", "Non-Critical"),
        "P0060" to DTCInfo("HO2S Heater Resistance (Bank 2 Sensor 2)", "Non-Critical"),
        "P0061" to DTCInfo("HO2S Heater Resistance (Bank 2 Sensor 3)", "Non-Critical"),
        "P0062" to DTCInfo("HO2S Heater Control Circuit (Bank 2 Sensor 3)", "Non-Critical"),
        "P0063" to DTCInfo("HO2S Heater Control Circuit Low (Bank 2 Sensor 3)", "Non-Critical"),
        "P0064" to DTCInfo("HO2S Heater Control Circuit High (Bank 2 Sensor 3)", "Non-Critical"),
        "P0065" to DTCInfo("Air Assisted Injector Control Range/Performance", "Important"),
        "P0066" to DTCInfo("Air Assisted Injector Control Circuit Low", "Important"),
        "P0067" to DTCInfo("Air Assisted Injector Control Circuit High", "Important"),
        "P0068" to DTCInfo("MAP/MAF - Throttle Position Correlation", "Important"),
        "P0069" to DTCInfo("Manifold Absolute Pressure - Barometric Pressure Correlation", "Important"),
        "P0070" to DTCInfo("Ambient Air Temperature Sensor Circuit", "Non-Critical"),
        "P0071" to DTCInfo("Ambient Air Temperature Sensor Range/Performance", "Non-Critical"),
        "P0072" to DTCInfo("Ambient Air Temperature Sensor Circuit Low", "Non-Critical"),
        "P0073" to DTCInfo("Ambient Air Temperature Sensor Circuit High", "Non-Critical"),
        "P0074" to DTCInfo("Ambient Air Temperature Sensor Circuit Intermittent", "Non-Critical"),
        "P0075" to DTCInfo("Intake Valve Control Solenoid Circuit (Bank 1)", "Important"),
        "P0076" to DTCInfo("Intake Valve Control Solenoid Circuit Low (Bank 1)", "Important"),
        "P0077" to DTCInfo("Intake Valve Control Solenoid Circuit High (Bank 1)", "Important"),
        "P0078" to DTCInfo("Exhaust Valve Control Solenoid Circuit (Bank 1)", "Important"),
        "P0079" to DTCInfo("Exhaust Valve Control Solenoid Circuit Low (Bank 1)", "Important"),
        "P0080" to DTCInfo("Exhaust Valve Control Solenoid Circuit High (Bank 1)", "Important"),
        "P0081" to DTCInfo("Intake Valve Control Solenoid Circuit (Bank 2)", "Important"),
        "P0082" to DTCInfo("Intake Valve Control Solenoid Circuit Low (Bank 2)", "Important"),
        "P0083" to DTCInfo("Intake Valve Control Solenoid Circuit High (Bank 2)", "Important"),
        "P0084" to DTCInfo("Exhaust Valve Control Solenoid Circuit (Bank 2)", "Important"),
        "P0085" to DTCInfo("Exhaust Valve Control Solenoid Circuit Low (Bank 2)", "Important"),
        "P0086" to DTCInfo("Exhaust Valve Control Solenoid Circuit High (Bank 2)", "Important"),
        "P0087" to DTCInfo("Fuel Rail/System Pressure - Too Low", "Critical"),
        "P0088" to DTCInfo("Fuel Rail/System Pressure - Too High", "Critical"),
        "P0089" to DTCInfo("Fuel Pressure Regulator 1 Performance", "Important"),
        "P0090" to DTCInfo("Fuel Pressure Regulator 1 Control Circuit", "Important"),
        "P0091" to DTCInfo("Fuel Pressure Regulator 1 Control Circuit Low", "Important"),
        "P0092" to DTCInfo("Fuel Pressure Regulator 1 Control Circuit High", "Important"),
        "P0093" to DTCInfo("Fuel System Leak Detected - Large Leak", "Critical"),
        "P0094" to DTCInfo("Fuel System Leak Detected - Small Leak", "Important"),
        "P0095" to DTCInfo("Intake Air Temperature Sensor 2 Circuit", "Non-Critical"),
        "P0096" to DTCInfo("Intake Air Temperature Sensor 2 Circuit Range/Performance", "Non-Critical"),
        "P0097" to DTCInfo("Intake Air Temperature Sensor 2 Circuit Low", "Non-Critical"),
        "P0098" to DTCInfo("Intake Air Temperature Sensor 2 Circuit High", "Non-Critical"),
        "P0099" to DTCInfo("Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic", "Non-Critical"),
        
        // P01xx - Fuel and Air Metering
        "P0100" to DTCInfo("Mass or Volume Air Flow Circuit", "Important"),
        "P0101" to DTCInfo("Mass or Volume Air Flow Circuit Range/Performance", "Important"),
        "P0102" to DTCInfo("Mass or Volume Air Flow Circuit Low Input", "Important"),
        "P0103" to DTCInfo("Mass or Volume Air Flow Circuit High Input", "Important"),
        "P0104" to DTCInfo("Mass or Volume Air Flow Circuit Intermittent", "Important"),
        "P0105" to DTCInfo("Manifold Absolute Pressure/Barometric Pressure Circuit", "Important"),
        "P0106" to DTCInfo("Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance", "Important"),
        "P0107" to DTCInfo("Manifold Absolute Pressure/Barometric Pressure Circuit Low Input", "Important"),
        "P0108" to DTCInfo("Manifold Absolute Pressure/Barometric Pressure Circuit High Input", "Important"),
        "P0109" to DTCInfo("Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent", "Important"),
        "P0110" to DTCInfo("Intake Air Temperature Circuit", "Non-Critical"),
        "P0111" to DTCInfo("Intake Air Temperature Circuit Range/Performance", "Non-Critical"),
        "P0112" to DTCInfo("Intake Air Temperature Circuit Low Input", "Non-Critical"),
        "P0113" to DTCInfo("Intake Air Temperature Circuit High Input", "Non-Critical"),
        "P0114" to DTCInfo("Intake Air Temperature Circuit Intermittent", "Non-Critical"),
        "P0115" to DTCInfo("Engine Coolant Temperature Circuit", "Important"),
        "P0116" to DTCInfo("Engine Coolant Temperature Circuit Range/Performance", "Important"),
        "P0117" to DTCInfo("Engine Coolant Temperature Circuit Low Input", "Important"),
        "P0118" to DTCInfo("Engine Coolant Temperature Circuit High Input", "Important"),
        "P0119" to DTCInfo("Engine Coolant Temperature Circuit Intermittent", "Important"),
        "P0120" to DTCInfo("Throttle/Pedal Position Sensor/Switch A Circuit", "Critical"),
        "P0121" to DTCInfo("Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance", "Critical"),
        "P0122" to DTCInfo("Throttle/Pedal Position Sensor/Switch A Circuit Low Input", "Critical"),
        "P0123" to DTCInfo("Throttle/Pedal Position Sensor/Switch A Circuit High Input", "Critical"),
        "P0124" to DTCInfo("Throttle/Pedal Position Sensor/Switch A Circuit Intermittent", "Critical"),
        "P0125" to DTCInfo("Insufficient Coolant Temperature for Closed Loop Fuel Control", "Non-Critical"),
        "P0126" to DTCInfo("Insufficient Coolant Temperature for Stable Operation", "Non-Critical"),
        "P0127" to DTCInfo("Intake Air Temperature Too High", "Important"),
        "P0128" to DTCInfo("Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)", "Non-Critical"),
        "P0129" to DTCInfo("Barometric Pressure Too Low", "Non-Critical"),
        "P0130" to DTCInfo("O2 Sensor Circuit (Bank 1 Sensor 1)", "Important"),
        "P0131" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)", "Important"),
        "P0132" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)", "Important"),
        "P0133" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)", "Important"),
        "P0134" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)", "Important"),
        "P0135" to DTCInfo("O2 Sensor Heater Circuit (Bank 1 Sensor 1)", "Important"),
        "P0136" to DTCInfo("O2 Sensor Circuit (Bank 1 Sensor 2)", "Important"),
        "P0137" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)", "Important"),
        "P0138" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)", "Important"),
        "P0139" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)", "Important"),
        "P0140" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)", "Important"),
        "P0141" to DTCInfo("O2 Sensor Heater Circuit (Bank 1 Sensor 2)", "Important"),
        "P0142" to DTCInfo("O2 Sensor Circuit (Bank 1 Sensor 3)", "Non-Critical"),
        "P0143" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 1 Sensor 3)", "Non-Critical"),
        "P0144" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 1 Sensor 3)", "Non-Critical"),
        "P0145" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 1 Sensor 3)", "Non-Critical"),
        "P0146" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 3)", "Non-Critical"),
        "P0147" to DTCInfo("O2 Sensor Heater Circuit (Bank 1 Sensor 3)", "Non-Critical"),
        "P0148" to DTCInfo("Fuel Delivery Error", "Critical"),
        "P0149" to DTCInfo("Fuel Timing Error", "Critical"),
        "P0150" to DTCInfo("O2 Sensor Circuit (Bank 2 Sensor 1)", "Important"),
        "P0151" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)", "Important"),
        "P0152" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)", "Important"),
        "P0153" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)", "Important"),
        "P0154" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)", "Important"),
        "P0155" to DTCInfo("O2 Sensor Heater Circuit (Bank 2 Sensor 1)", "Important"),
        "P0156" to DTCInfo("O2 Sensor Circuit (Bank 2 Sensor 2)", "Important"),
        "P0157" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 2 Sensor 2)", "Important"),
        "P0158" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)", "Important"),
        "P0159" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 2 Sensor 2)", "Important"),
        "P0160" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)", "Important"),
        "P0161" to DTCInfo("O2 Sensor Heater Circuit (Bank 2 Sensor 2)", "Important"),
        "P0162" to DTCInfo("O2 Sensor Circuit (Bank 2 Sensor 3)", "Non-Critical"),
        "P0163" to DTCInfo("O2 Sensor Circuit Low Voltage (Bank 2 Sensor 3)", "Non-Critical"),
        "P0164" to DTCInfo("O2 Sensor Circuit High Voltage (Bank 2 Sensor 3)", "Non-Critical"),
        "P0165" to DTCInfo("O2 Sensor Circuit Slow Response (Bank 2 Sensor 3)", "Non-Critical"),
        "P0166" to DTCInfo("O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 3)", "Non-Critical"),
        "P0167" to DTCInfo("O2 Sensor Heater Circuit (Bank 2 Sensor 3)", "Non-Critical"),
        "P0168" to DTCInfo("Fuel Temperature Too High", "Important"),
        "P0169" to DTCInfo("Incorrect Fuel Composition", "Important"),
        "P0170" to DTCInfo("Fuel Trim (Bank 1)", "Important"),
        "P0171" to DTCInfo("System Too Lean (Bank 1)", "Important"),
        "P0172" to DTCInfo("System Too Rich (Bank 1)", "Important"),
        "P0173" to DTCInfo("Fuel Trim (Bank 2)", "Important"),
        "P0174" to DTCInfo("System Too Lean (Bank 2)", "Important"),
        "P0175" to DTCInfo("System Too Rich (Bank 2)", "Important"),
        "P0176" to DTCInfo("Fuel Composition Sensor Circuit", "Non-Critical"),
        "P0177" to DTCInfo("Fuel Composition Sensor Circuit Range/Performance", "Non-Critical"),
        "P0178" to DTCInfo("Fuel Composition Sensor Circuit Low Input", "Non-Critical"),
        "P0179" to DTCInfo("Fuel Composition Sensor Circuit High Input", "Non-Critical"),
        "P0180" to DTCInfo("Fuel Temperature Sensor A Circuit", "Non-Critical"),
        "P0181" to DTCInfo("Fuel Temperature Sensor A Circuit Range/Performance", "Non-Critical"),
        "P0182" to DTCInfo("Fuel Temperature Sensor A Circuit Low Input", "Non-Critical"),
        "P0183" to DTCInfo("Fuel Temperature Sensor A Circuit High Input", "Non-Critical"),
        "P0184" to DTCInfo("Fuel Temperature Sensor A Circuit Intermittent", "Non-Critical"),
        "P0185" to DTCInfo("Fuel Temperature Sensor B Circuit", "Non-Critical"),
        "P0186" to DTCInfo("Fuel Temperature Sensor B Circuit Range/Performance", "Non-Critical"),
        "P0187" to DTCInfo("Fuel Temperature Sensor B Circuit Low Input", "Non-Critical"),
        "P0188" to DTCInfo("Fuel Temperature Sensor B Circuit High Input", "Non-Critical"),
        "P0189" to DTCInfo("Fuel Temperature Sensor B Circuit Intermittent", "Non-Critical"),
        "P0190" to DTCInfo("Fuel Rail Pressure Sensor Circuit", "Important"),
        "P0191" to DTCInfo("Fuel Rail Pressure Sensor Circuit Range/Performance", "Important"),
        "P0192" to DTCInfo("Fuel Rail Pressure Sensor Circuit Low Input", "Important"),
        "P0193" to DTCInfo("Fuel Rail Pressure Sensor Circuit High Input", "Important"),
        "P0194" to DTCInfo("Fuel Rail Pressure Sensor Circuit Intermittent", "Important"),
        "P0195" to DTCInfo("Engine Oil Temperature Sensor", "Non-Critical"),
        "P0196" to DTCInfo("Engine Oil Temperature Sensor Range/Performance", "Non-Critical"),
        "P0197" to DTCInfo("Engine Oil Temperature Sensor Low", "Non-Critical"),
        "P0198" to DTCInfo("Engine Oil Temperature Sensor High", "Non-Critical"),
        "P0199" to DTCInfo("Engine Oil Temperature Sensor Intermittent", "Non-Critical")
    )
}
