package com.wisedrive.obd2.constants

/**
 * DTC Descriptions - Part 3: Powertrain P04xx-P09xx (Emissions, Vehicle Speed, Idle, Computer)
 */
object DTCDescriptionsP2 {
    
    val P04_CODES: Map<String, DTCInfo> = mapOf(
        // P04xx - Auxiliary Emissions Controls
        "P0400" to DTCInfo("Exhaust Gas Recirculation Flow", "Important"),
        "P0401" to DTCInfo("Exhaust Gas Recirculation Flow Insufficient Detected", "Important"),
        "P0402" to DTCInfo("Exhaust Gas Recirculation Flow Excessive Detected", "Important"),
        "P0403" to DTCInfo("Exhaust Gas Recirculation Circuit", "Important"),
        "P0404" to DTCInfo("Exhaust Gas Recirculation Circuit Range/Performance", "Important"),
        "P0405" to DTCInfo("Exhaust Gas Recirculation Sensor A Circuit Low", "Important"),
        "P0406" to DTCInfo("Exhaust Gas Recirculation Sensor A Circuit High", "Important"),
        "P0407" to DTCInfo("Exhaust Gas Recirculation Sensor B Circuit Low", "Important"),
        "P0408" to DTCInfo("Exhaust Gas Recirculation Sensor B Circuit High", "Important"),
        "P0409" to DTCInfo("Exhaust Gas Recirculation Sensor A Circuit", "Important"),
        "P0410" to DTCInfo("Secondary Air Injection System", "Non-Critical"),
        "P0411" to DTCInfo("Secondary Air Injection System Incorrect Flow Detected", "Non-Critical"),
        "P0412" to DTCInfo("Secondary Air Injection System Switching Valve A Circuit", "Non-Critical"),
        "P0413" to DTCInfo("Secondary Air Injection System Switching Valve A Circuit Open", "Non-Critical"),
        "P0414" to DTCInfo("Secondary Air Injection System Switching Valve A Circuit Shorted", "Non-Critical"),
        "P0415" to DTCInfo("Secondary Air Injection System Switching Valve B Circuit", "Non-Critical"),
        "P0416" to DTCInfo("Secondary Air Injection System Switching Valve B Circuit Open", "Non-Critical"),
        "P0417" to DTCInfo("Secondary Air Injection System Switching Valve B Circuit Shorted", "Non-Critical"),
        "P0418" to DTCInfo("Secondary Air Injection System Relay A Circuit", "Non-Critical"),
        "P0419" to DTCInfo("Secondary Air Injection System Relay B Circuit", "Non-Critical"),
        "P0420" to DTCInfo("Catalyst System Efficiency Below Threshold (Bank 1)", "Important"),
        "P0421" to DTCInfo("Warm Up Catalyst Efficiency Below Threshold (Bank 1)", "Important"),
        "P0422" to DTCInfo("Main Catalyst Efficiency Below Threshold (Bank 1)", "Important"),
        "P0423" to DTCInfo("Heated Catalyst Efficiency Below Threshold (Bank 1)", "Important"),
        "P0424" to DTCInfo("Heated Catalyst Temperature Below Threshold (Bank 1)", "Non-Critical"),
        "P0425" to DTCInfo("Catalyst Temperature Sensor (Bank 1)", "Non-Critical"),
        "P0426" to DTCInfo("Catalyst Temperature Sensor Range/Performance (Bank 1)", "Non-Critical"),
        "P0427" to DTCInfo("Catalyst Temperature Sensor Low Input (Bank 1)", "Non-Critical"),
        "P0428" to DTCInfo("Catalyst Temperature Sensor High Input (Bank 1)", "Non-Critical"),
        "P0429" to DTCInfo("Catalyst Heater Control Circuit (Bank 1)", "Non-Critical"),
        "P0430" to DTCInfo("Catalyst System Efficiency Below Threshold (Bank 2)", "Important"),
        "P0431" to DTCInfo("Warm Up Catalyst Efficiency Below Threshold (Bank 2)", "Important"),
        "P0432" to DTCInfo("Main Catalyst Efficiency Below Threshold (Bank 2)", "Important"),
        "P0433" to DTCInfo("Heated Catalyst Efficiency Below Threshold (Bank 2)", "Important"),
        "P0434" to DTCInfo("Heated Catalyst Temperature Below Threshold (Bank 2)", "Non-Critical"),
        "P0435" to DTCInfo("Catalyst Temperature Sensor (Bank 2)", "Non-Critical"),
        "P0436" to DTCInfo("Catalyst Temperature Sensor Range/Performance (Bank 2)", "Non-Critical"),
        "P0437" to DTCInfo("Catalyst Temperature Sensor Low Input (Bank 2)", "Non-Critical"),
        "P0438" to DTCInfo("Catalyst Temperature Sensor High Input (Bank 2)", "Non-Critical"),
        "P0439" to DTCInfo("Catalyst Heater Control Circuit (Bank 2)", "Non-Critical"),
        "P0440" to DTCInfo("Evaporative Emission Control System", "Non-Critical"),
        "P0441" to DTCInfo("Evaporative Emission Control System Incorrect Purge Flow", "Non-Critical"),
        "P0442" to DTCInfo("Evaporative Emission Control System Leak Detected (small leak)", "Non-Critical"),
        "P0443" to DTCInfo("Evaporative Emission Control System Purge Control Valve Circuit", "Non-Critical"),
        "P0444" to DTCInfo("Evaporative Emission Control System Purge Control Valve Circuit Open", "Non-Critical"),
        "P0445" to DTCInfo("Evaporative Emission Control System Purge Control Valve Circuit Shorted", "Non-Critical"),
        "P0446" to DTCInfo("Evaporative Emission Control System Vent Control Circuit", "Non-Critical"),
        "P0447" to DTCInfo("Evaporative Emission Control System Vent Control Circuit Open", "Non-Critical"),
        "P0448" to DTCInfo("Evaporative Emission Control System Vent Control Circuit Shorted", "Non-Critical"),
        "P0449" to DTCInfo("Evaporative Emission Control System Vent Valve/Solenoid Circuit", "Non-Critical"),
        "P0450" to DTCInfo("Evaporative Emission Control System Pressure Sensor", "Non-Critical"),
        "P0451" to DTCInfo("Evaporative Emission Control System Pressure Sensor Range/Performance", "Non-Critical"),
        "P0452" to DTCInfo("Evaporative Emission Control System Pressure Sensor Low Input", "Non-Critical"),
        "P0453" to DTCInfo("Evaporative Emission Control System Pressure Sensor High Input", "Non-Critical"),
        "P0454" to DTCInfo("Evaporative Emission Control System Pressure Sensor Intermittent", "Non-Critical"),
        "P0455" to DTCInfo("Evaporative Emission Control System Leak Detected (large leak)", "Non-Critical"),
        "P0456" to DTCInfo("Evaporative Emission Control System Leak Detected (very small leak)", "Non-Critical"),
        "P0457" to DTCInfo("Evaporative Emission Control System Leak Detected (fuel cap loose/off)", "Non-Critical"),
        "P0458" to DTCInfo("Evaporative Emission Control System Purge Control Valve Circuit Low", "Non-Critical"),
        "P0459" to DTCInfo("Evaporative Emission Control System Purge Control Valve Circuit High", "Non-Critical"),
        "P0460" to DTCInfo("Fuel Level Sensor Circuit", "Non-Critical"),
        "P0461" to DTCInfo("Fuel Level Sensor Circuit Range/Performance", "Non-Critical"),
        "P0462" to DTCInfo("Fuel Level Sensor Circuit Low Input", "Non-Critical"),
        "P0463" to DTCInfo("Fuel Level Sensor Circuit High Input", "Non-Critical"),
        "P0464" to DTCInfo("Fuel Level Sensor Circuit Intermittent", "Non-Critical"),
        "P0465" to DTCInfo("Purge Flow Sensor Circuit", "Non-Critical"),
        "P0466" to DTCInfo("Purge Flow Sensor Circuit Range/Performance", "Non-Critical"),
        "P0467" to DTCInfo("Purge Flow Sensor Circuit Low Input", "Non-Critical"),
        "P0468" to DTCInfo("Purge Flow Sensor Circuit High Input", "Non-Critical"),
        "P0469" to DTCInfo("Purge Flow Sensor Circuit Intermittent", "Non-Critical"),
        "P0470" to DTCInfo("Exhaust Pressure Sensor", "Important"),
        "P0471" to DTCInfo("Exhaust Pressure Sensor Range/Performance", "Important"),
        "P0472" to DTCInfo("Exhaust Pressure Sensor Low", "Important"),
        "P0473" to DTCInfo("Exhaust Pressure Sensor High", "Important"),
        "P0474" to DTCInfo("Exhaust Pressure Sensor Intermittent", "Important"),
        "P0475" to DTCInfo("Exhaust Pressure Control Valve", "Important"),
        "P0476" to DTCInfo("Exhaust Pressure Control Valve Range/Performance", "Important"),
        "P0477" to DTCInfo("Exhaust Pressure Control Valve Low", "Important"),
        "P0478" to DTCInfo("Exhaust Pressure Control Valve High", "Important"),
        "P0479" to DTCInfo("Exhaust Pressure Control Valve Intermittent", "Important"),
        "P0480" to DTCInfo("Cooling Fan 1 Control Circuit", "Important"),
        "P0481" to DTCInfo("Cooling Fan 2 Control Circuit", "Important"),
        "P0482" to DTCInfo("Cooling Fan 3 Control Circuit", "Important"),
        "P0483" to DTCInfo("Cooling Fan Rationality Check", "Non-Critical"),
        "P0484" to DTCInfo("Cooling Fan Circuit Over Current", "Important"),
        "P0485" to DTCInfo("Cooling Fan Power/Ground Circuit", "Important"),
        "P0486" to DTCInfo("Exhaust Gas Recirculation Sensor B Circuit", "Important"),
        "P0487" to DTCInfo("Exhaust Gas Recirculation Throttle Position Control Circuit", "Important"),
        "P0488" to DTCInfo("Exhaust Gas Recirculation Throttle Position Control Range/Performance", "Important"),
        "P0489" to DTCInfo("Exhaust Gas Recirculation Control Circuit Low", "Important"),
        "P0490" to DTCInfo("Exhaust Gas Recirculation Control Circuit High", "Important"),
        "P0491" to DTCInfo("Secondary Air Injection System (Bank 1)", "Non-Critical"),
        "P0492" to DTCInfo("Secondary Air Injection System (Bank 2)", "Non-Critical"),
        "P0493" to DTCInfo("Fan Overspeed", "Important"),
        "P0494" to DTCInfo("Fan Speed Low", "Non-Critical"),
        "P0495" to DTCInfo("Fan Speed High", "Non-Critical"),
        "P0496" to DTCInfo("Evaporative Emission Control System High Purge Flow", "Non-Critical"),
        "P0497" to DTCInfo("Evaporative Emission Control System Low Purge Flow", "Non-Critical"),
        "P0498" to DTCInfo("Evaporative Emission Control System Vent Valve Control Circuit Low", "Non-Critical"),
        "P0499" to DTCInfo("Evaporative Emission Control System Vent Valve Control Circuit High", "Non-Critical")
    )

    val P05_CODES: Map<String, DTCInfo> = mapOf(
        // P05xx - Vehicle Speed Controls and Idle Control System
        "P0500" to DTCInfo("Vehicle Speed Sensor", "Important"),
        "P0501" to DTCInfo("Vehicle Speed Sensor Range/Performance", "Important"),
        "P0502" to DTCInfo("Vehicle Speed Sensor Circuit Low Input", "Important"),
        "P0503" to DTCInfo("Vehicle Speed Sensor Intermittent/Erratic/High", "Important"),
        "P0504" to DTCInfo("Brake Switch A/B Correlation", "Important"),
        "P0505" to DTCInfo("Idle Control System", "Important"),
        "P0506" to DTCInfo("Idle Control System RPM Lower Than Expected", "Non-Critical"),
        "P0507" to DTCInfo("Idle Control System RPM Higher Than Expected", "Non-Critical"),
        "P0508" to DTCInfo("Idle Air Control System Circuit Low", "Important"),
        "P0509" to DTCInfo("Idle Air Control System Circuit High", "Important"),
        "P0510" to DTCInfo("Closed Throttle Position Switch", "Important"),
        "P0511" to DTCInfo("Idle Air Control Circuit", "Important"),
        "P0512" to DTCInfo("Starter Request Circuit", "Important"),
        "P0513" to DTCInfo("Incorrect Immobilizer Key", "Critical"),
        "P0514" to DTCInfo("Battery Temperature Sensor Circuit Range/Performance", "Non-Critical"),
        "P0515" to DTCInfo("Battery Temperature Sensor Circuit", "Non-Critical"),
        "P0516" to DTCInfo("Battery Temperature Sensor Circuit Low", "Non-Critical"),
        "P0517" to DTCInfo("Battery Temperature Sensor Circuit High", "Non-Critical"),
        "P0518" to DTCInfo("Idle Air Control Circuit Intermittent", "Important"),
        "P0519" to DTCInfo("Idle Air Control System Performance", "Important"),
        "P0520" to DTCInfo("Engine Oil Pressure Sensor/Switch Circuit", "Important"),
        "P0521" to DTCInfo("Engine Oil Pressure Sensor/Switch Range/Performance", "Important"),
        "P0522" to DTCInfo("Engine Oil Pressure Sensor/Switch Low Voltage", "Important"),
        "P0523" to DTCInfo("Engine Oil Pressure Sensor/Switch High Voltage", "Important"),
        "P0524" to DTCInfo("Engine Oil Pressure Too Low", "Critical"),
        "P0525" to DTCInfo("Cruise Control Servo Control Circuit Range/Performance", "Non-Critical"),
        "P0526" to DTCInfo("Fan Speed Sensor Circuit", "Non-Critical"),
        "P0527" to DTCInfo("Fan Speed Sensor Circuit Range/Performance", "Non-Critical"),
        "P0528" to DTCInfo("Fan Speed Sensor Circuit No Signal", "Non-Critical"),
        "P0529" to DTCInfo("Fan Speed Sensor Circuit Intermittent", "Non-Critical"),
        "P0530" to DTCInfo("A/C Refrigerant Pressure Sensor Circuit", "Non-Critical"),
        "P0531" to DTCInfo("A/C Refrigerant Pressure Sensor Circuit Range/Performance", "Non-Critical"),
        "P0532" to DTCInfo("A/C Refrigerant Pressure Sensor Circuit Low Input", "Non-Critical"),
        "P0533" to DTCInfo("A/C Refrigerant Pressure Sensor Circuit High Input", "Non-Critical"),
        "P0534" to DTCInfo("Air Conditioner Refrigerant Charge Loss", "Non-Critical"),
        "P0535" to DTCInfo("A/C Evaporator Temperature Sensor Circuit", "Non-Critical"),
        "P0536" to DTCInfo("A/C Evaporator Temperature Sensor Circuit Range/Performance", "Non-Critical"),
        "P0537" to DTCInfo("A/C Evaporator Temperature Sensor Circuit Low", "Non-Critical"),
        "P0538" to DTCInfo("A/C Evaporator Temperature Sensor Circuit High", "Non-Critical"),
        "P0539" to DTCInfo("A/C Evaporator Temperature Sensor Circuit Intermittent", "Non-Critical"),
        "P0540" to DTCInfo("Intake Air Heater A Circuit", "Non-Critical"),
        "P0541" to DTCInfo("Intake Air Heater A Circuit Low", "Non-Critical"),
        "P0542" to DTCInfo("Intake Air Heater A Circuit High", "Non-Critical"),
        "P0543" to DTCInfo("Intake Air Heater A Circuit Open", "Non-Critical"),
        "P0544" to DTCInfo("Exhaust Gas Temperature Sensor Circuit (Bank 1 Sensor 1)", "Important"),
        "P0545" to DTCInfo("Exhaust Gas Temperature Sensor Circuit Low (Bank 1 Sensor 1)", "Important"),
        "P0546" to DTCInfo("Exhaust Gas Temperature Sensor Circuit High (Bank 1 Sensor 1)", "Important"),
        "P0547" to DTCInfo("Exhaust Gas Temperature Sensor Circuit (Bank 2 Sensor 1)", "Important"),
        "P0548" to DTCInfo("Exhaust Gas Temperature Sensor Circuit Low (Bank 2 Sensor 1)", "Important"),
        "P0549" to DTCInfo("Exhaust Gas Temperature Sensor Circuit High (Bank 2 Sensor 1)", "Important"),
        "P0550" to DTCInfo("Power Steering Pressure Sensor Circuit", "Non-Critical"),
        "P0551" to DTCInfo("Power Steering Pressure Sensor Circuit Range/Performance", "Non-Critical"),
        "P0552" to DTCInfo("Power Steering Pressure Sensor Circuit Low Input", "Non-Critical"),
        "P0553" to DTCInfo("Power Steering Pressure Sensor Circuit High Input", "Non-Critical"),
        "P0554" to DTCInfo("Power Steering Pressure Sensor Circuit Intermittent", "Non-Critical"),
        "P0555" to DTCInfo("Brake Booster Pressure Sensor Circuit", "Important"),
        "P0556" to DTCInfo("Brake Booster Pressure Sensor Circuit Range/Performance", "Important"),
        "P0557" to DTCInfo("Brake Booster Pressure Sensor Circuit Low Input", "Important"),
        "P0558" to DTCInfo("Brake Booster Pressure Sensor Circuit High Input", "Important"),
        "P0559" to DTCInfo("Brake Booster Pressure Sensor Circuit Intermittent", "Important"),
        "P0560" to DTCInfo("System Voltage", "Important"),
        "P0561" to DTCInfo("System Voltage Unstable", "Important"),
        "P0562" to DTCInfo("System Voltage Low", "Important"),
        "P0563" to DTCInfo("System Voltage High", "Important"),
        "P0564" to DTCInfo("Cruise Control Multi-Function Input A Circuit", "Non-Critical"),
        "P0565" to DTCInfo("Cruise Control On Signal", "Non-Critical"),
        "P0566" to DTCInfo("Cruise Control Off Signal", "Non-Critical"),
        "P0567" to DTCInfo("Cruise Control Resume Signal", "Non-Critical"),
        "P0568" to DTCInfo("Cruise Control Set Signal", "Non-Critical"),
        "P0569" to DTCInfo("Cruise Control Coast Signal", "Non-Critical"),
        "P0570" to DTCInfo("Cruise Control Accel Signal", "Non-Critical"),
        "P0571" to DTCInfo("Cruise Control/Brake Switch A Circuit", "Non-Critical"),
        "P0572" to DTCInfo("Cruise Control/Brake Switch A Circuit Low", "Non-Critical"),
        "P0573" to DTCInfo("Cruise Control/Brake Switch A Circuit High", "Non-Critical"),
        "P0574" to DTCInfo("Cruise Control System - Vehicle Speed Too High", "Non-Critical"),
        "P0575" to DTCInfo("Cruise Control Input Circuit", "Non-Critical"),
        "P0576" to DTCInfo("Cruise Control Input Circuit Low", "Non-Critical"),
        "P0577" to DTCInfo("Cruise Control Input Circuit High", "Non-Critical"),
        "P0578" to DTCInfo("Cruise Control Multi-Function Input A Circuit Stuck", "Non-Critical"),
        "P0579" to DTCInfo("Cruise Control Multi-Function Input A Circuit Range/Performance", "Non-Critical"),
        "P0580" to DTCInfo("Cruise Control Multi-Function Input A Circuit Low", "Non-Critical"),
        "P0581" to DTCInfo("Cruise Control Multi-Function Input A Circuit High", "Non-Critical"),
        "P0582" to DTCInfo("Cruise Control Vacuum Control Circuit/Open", "Non-Critical"),
        "P0583" to DTCInfo("Cruise Control Vacuum Control Circuit Low", "Non-Critical"),
        "P0584" to DTCInfo("Cruise Control Vacuum Control Circuit High", "Non-Critical"),
        "P0585" to DTCInfo("Cruise Control Multi-Function Input A/B Correlation", "Non-Critical"),
        "P0586" to DTCInfo("Cruise Control Vent Control Circuit/Open", "Non-Critical"),
        "P0587" to DTCInfo("Cruise Control Vent Control Circuit Low", "Non-Critical"),
        "P0588" to DTCInfo("Cruise Control Vent Control Circuit High", "Non-Critical"),
        "P0589" to DTCInfo("Cruise Control Multi-Function Input B Circuit", "Non-Critical"),
        "P0590" to DTCInfo("Cruise Control Multi-Function Input B Circuit Stuck", "Non-Critical"),
        "P0591" to DTCInfo("Cruise Control Multi-Function Input B Circuit Range/Performance", "Non-Critical"),
        "P0592" to DTCInfo("Cruise Control Multi-Function Input B Circuit Low", "Non-Critical"),
        "P0593" to DTCInfo("Cruise Control Multi-Function Input B Circuit High", "Non-Critical"),
        "P0594" to DTCInfo("Cruise Control Servo Control Circuit/Open", "Non-Critical"),
        "P0595" to DTCInfo("Cruise Control Servo Control Circuit Low", "Non-Critical"),
        "P0596" to DTCInfo("Cruise Control Servo Control Circuit High", "Non-Critical"),
        "P0597" to DTCInfo("Thermostat Heater Control Circuit/Open", "Non-Critical"),
        "P0598" to DTCInfo("Thermostat Heater Control Circuit Low", "Non-Critical"),
        "P0599" to DTCInfo("Thermostat Heater Control Circuit High", "Non-Critical")
    )

    val P06_CODES: Map<String, DTCInfo> = mapOf(
        // P06xx - Computer Output Circuit
        "P0600" to DTCInfo("Serial Communication Link", "Critical"),
        "P0601" to DTCInfo("Internal Control Module Memory Check Sum Error", "Critical"),
        "P0602" to DTCInfo("Control Module Programming Error", "Critical"),
        "P0603" to DTCInfo("Internal Control Module Keep Alive Memory (KAM) Error", "Critical"),
        "P0604" to DTCInfo("Internal Control Module Random Access Memory (RAM) Error", "Critical"),
        "P0605" to DTCInfo("Internal Control Module Read Only Memory (ROM) Error", "Critical"),
        "P0606" to DTCInfo("ECM/PCM Processor", "Critical"),
        "P0607" to DTCInfo("Control Module Performance", "Critical"),
        "P0608" to DTCInfo("Control Module VSS Output A", "Important"),
        "P0609" to DTCInfo("Control Module VSS Output B", "Important"),
        "P0610" to DTCInfo("Control Module Vehicle Options Error", "Important"),
        "P0611" to DTCInfo("Fuel Injector Control Module Performance", "Critical"),
        "P0612" to DTCInfo("Fuel Injector Control Module Relay Control", "Critical"),
        "P0613" to DTCInfo("TCM Processor", "Critical"),
        "P0614" to DTCInfo("ECM/TCM Incompatible", "Critical"),
        "P0615" to DTCInfo("Starter Relay Circuit", "Important"),
        "P0616" to DTCInfo("Starter Relay Circuit Low", "Important"),
        "P0617" to DTCInfo("Starter Relay Circuit High", "Important"),
        "P0618" to DTCInfo("Alternative Fuel Control Module KAM Error", "Important"),
        "P0619" to DTCInfo("Alternative Fuel Control Module RAM/ROM Error", "Important"),
        "P0620" to DTCInfo("Generator Control Circuit", "Important"),
        "P0621" to DTCInfo("Generator Lamp L Control Circuit", "Non-Critical"),
        "P0622" to DTCInfo("Generator Field F Control Circuit", "Important"),
        "P0623" to DTCInfo("Generator Lamp Control Circuit", "Non-Critical"),
        "P0624" to DTCInfo("Fuel Cap Lamp Control Circuit", "Non-Critical"),
        "P0625" to DTCInfo("Generator Field Terminal Circuit Low", "Important"),
        "P0626" to DTCInfo("Generator Field Terminal Circuit High", "Important"),
        "P0627" to DTCInfo("Fuel Pump A Control Circuit/Open", "Critical"),
        "P0628" to DTCInfo("Fuel Pump A Control Circuit Low", "Critical"),
        "P0629" to DTCInfo("Fuel Pump A Control Circuit High", "Critical"),
        "P0630" to DTCInfo("VIN Not Programmed or Incompatible - ECM/PCM", "Critical"),
        "P0631" to DTCInfo("VIN Not Programmed or Incompatible - TCM", "Critical"),
        "P0632" to DTCInfo("Odometer Not Programmed - ECM/PCM", "Non-Critical"),
        "P0633" to DTCInfo("Immobilizer Key Not Programmed - ECM/PCM", "Critical"),
        "P0634" to DTCInfo("PCM/ECM/TCM Internal Temperature Too High", "Critical"),
        "P0635" to DTCInfo("Power Steering Control Circuit", "Important"),
        "P0636" to DTCInfo("Power Steering Control Circuit Low", "Important"),
        "P0637" to DTCInfo("Power Steering Control Circuit High", "Important"),
        "P0638" to DTCInfo("Throttle Actuator Control Range/Performance (Bank 1)", "Critical"),
        "P0639" to DTCInfo("Throttle Actuator Control Range/Performance (Bank 2)", "Critical"),
        "P0640" to DTCInfo("Intake Air Heater Control Circuit", "Non-Critical"),
        "P0641" to DTCInfo("Sensor Reference Voltage A Circuit/Open", "Important"),
        "P0642" to DTCInfo("Sensor Reference Voltage A Circuit Low", "Important"),
        "P0643" to DTCInfo("Sensor Reference Voltage A Circuit High", "Important"),
        "P0644" to DTCInfo("Driver Display Serial Communication Circuit", "Non-Critical"),
        "P0645" to DTCInfo("A/C Clutch Relay Control Circuit", "Non-Critical"),
        "P0646" to DTCInfo("A/C Clutch Relay Control Circuit Low", "Non-Critical"),
        "P0647" to DTCInfo("A/C Clutch Relay Control Circuit High", "Non-Critical"),
        "P0648" to DTCInfo("Immobilizer Lamp Control Circuit", "Non-Critical"),
        "P0649" to DTCInfo("Speed Control Lamp Control Circuit", "Non-Critical"),
        "P0650" to DTCInfo("Malfunction Indicator Lamp (MIL) Control Circuit", "Non-Critical"),
        "P0651" to DTCInfo("Sensor Reference Voltage B Circuit/Open", "Important"),
        "P0652" to DTCInfo("Sensor Reference Voltage B Circuit Low", "Important"),
        "P0653" to DTCInfo("Sensor Reference Voltage B Circuit High", "Important"),
        "P0654" to DTCInfo("Engine RPM Output Circuit", "Important"),
        "P0655" to DTCInfo("Engine Hot Lamp Output Control Circuit", "Non-Critical"),
        "P0656" to DTCInfo("Fuel Level Output Circuit", "Non-Critical"),
        "P0657" to DTCInfo("Actuator Supply Voltage A Circuit/Open", "Important"),
        "P0658" to DTCInfo("Actuator Supply Voltage A Circuit Low", "Important"),
        "P0659" to DTCInfo("Actuator Supply Voltage A Circuit High", "Important"),
        "P0660" to DTCInfo("Intake Manifold Tuning Valve Control Circuit/Open (Bank 1)", "Non-Critical"),
        "P0661" to DTCInfo("Intake Manifold Tuning Valve Control Circuit Low (Bank 1)", "Non-Critical"),
        "P0662" to DTCInfo("Intake Manifold Tuning Valve Control Circuit High (Bank 1)", "Non-Critical"),
        "P0663" to DTCInfo("Intake Manifold Tuning Valve Control Circuit/Open (Bank 2)", "Non-Critical"),
        "P0664" to DTCInfo("Intake Manifold Tuning Valve Control Circuit Low (Bank 2)", "Non-Critical"),
        "P0665" to DTCInfo("Intake Manifold Tuning Valve Control Circuit High (Bank 2)", "Non-Critical"),
        "P0666" to DTCInfo("PCM/ECM/TCM Internal Temperature Sensor Circuit", "Important"),
        "P0667" to DTCInfo("PCM/ECM/TCM Internal Temperature Sensor Range/Performance", "Important"),
        "P0668" to DTCInfo("PCM/ECM/TCM Internal Temperature Sensor Circuit Low", "Important"),
        "P0669" to DTCInfo("PCM/ECM/TCM Internal Temperature Sensor Circuit High", "Important"),
        "P0670" to DTCInfo("Glow Plug Module Control Circuit", "Important"),
        "P0671" to DTCInfo("Cylinder 1 Glow Plug Circuit", "Important"),
        "P0672" to DTCInfo("Cylinder 2 Glow Plug Circuit", "Important"),
        "P0673" to DTCInfo("Cylinder 3 Glow Plug Circuit", "Important"),
        "P0674" to DTCInfo("Cylinder 4 Glow Plug Circuit", "Important"),
        "P0675" to DTCInfo("Cylinder 5 Glow Plug Circuit", "Important"),
        "P0676" to DTCInfo("Cylinder 6 Glow Plug Circuit", "Important"),
        "P0677" to DTCInfo("Cylinder 7 Glow Plug Circuit", "Important"),
        "P0678" to DTCInfo("Cylinder 8 Glow Plug Circuit", "Important"),
        "P0679" to DTCInfo("Cylinder 9 Glow Plug Circuit", "Important"),
        "P0680" to DTCInfo("Cylinder 10 Glow Plug Circuit", "Important"),
        "P0681" to DTCInfo("Cylinder 11 Glow Plug Circuit", "Important"),
        "P0682" to DTCInfo("Cylinder 12 Glow Plug Circuit", "Important"),
        "P0683" to DTCInfo("Glow Plug Control Module to PCM Communication Circuit", "Important"),
        "P0684" to DTCInfo("Glow Plug Control Module to PCM Communication Circuit Range/Performance", "Important"),
        "P0685" to DTCInfo("ECM/PCM Power Relay Control Circuit/Open", "Critical"),
        "P0686" to DTCInfo("ECM/PCM Power Relay Control Circuit Low", "Critical"),
        "P0687" to DTCInfo("ECM/PCM Power Relay Control Circuit High", "Critical"),
        "P0688" to DTCInfo("ECM/PCM Power Relay Sense Circuit/Open", "Critical"),
        "P0689" to DTCInfo("ECM/PCM Power Relay Sense Circuit Low", "Critical"),
        "P0690" to DTCInfo("ECM/PCM Power Relay Sense Circuit High", "Critical"),
        "P0691" to DTCInfo("Fan 1 Control Circuit Low", "Important"),
        "P0692" to DTCInfo("Fan 1 Control Circuit High", "Important"),
        "P0693" to DTCInfo("Fan 2 Control Circuit Low", "Important"),
        "P0694" to DTCInfo("Fan 2 Control Circuit High", "Important"),
        "P0695" to DTCInfo("Fan 3 Control Circuit Low", "Non-Critical"),
        "P0696" to DTCInfo("Fan 3 Control Circuit High", "Non-Critical"),
        "P0697" to DTCInfo("Sensor Reference Voltage C Circuit/Open", "Important"),
        "P0698" to DTCInfo("Sensor Reference Voltage C Circuit Low", "Important"),
        "P0699" to DTCInfo("Sensor Reference Voltage C Circuit High", "Important")
    )

    val P07_CODES: Map<String, DTCInfo> = mapOf(
        // P07xx - Transmission
        "P0700" to DTCInfo("Transmission Control System", "Critical"),
        "P0701" to DTCInfo("Transmission Control System Range/Performance", "Critical"),
        "P0702" to DTCInfo("Transmission Control System Electrical", "Critical"),
        "P0703" to DTCInfo("Torque Converter/Brake Switch B Circuit", "Important"),
        "P0704" to DTCInfo("Clutch Switch Input Circuit", "Important"),
        "P0705" to DTCInfo("Transmission Range Sensor Circuit (PRNDL Input)", "Critical"),
        "P0706" to DTCInfo("Transmission Range Sensor Circuit Range/Performance", "Critical"),
        "P0707" to DTCInfo("Transmission Range Sensor Circuit Low Input", "Critical"),
        "P0708" to DTCInfo("Transmission Range Sensor Circuit High Input", "Critical"),
        "P0709" to DTCInfo("Transmission Range Sensor Circuit Intermittent", "Critical"),
        "P0710" to DTCInfo("Transmission Fluid Temperature Sensor Circuit", "Important"),
        "P0711" to DTCInfo("Transmission Fluid Temperature Sensor Circuit Range/Performance", "Important"),
        "P0712" to DTCInfo("Transmission Fluid Temperature Sensor Circuit Low Input", "Important"),
        "P0713" to DTCInfo("Transmission Fluid Temperature Sensor Circuit High Input", "Important"),
        "P0714" to DTCInfo("Transmission Fluid Temperature Sensor Circuit Intermittent", "Important"),
        "P0715" to DTCInfo("Input/Turbine Speed Sensor Circuit", "Critical"),
        "P0716" to DTCInfo("Input/Turbine Speed Sensor Circuit Range/Performance", "Critical"),
        "P0717" to DTCInfo("Input/Turbine Speed Sensor Circuit No Signal", "Critical"),
        "P0718" to DTCInfo("Input/Turbine Speed Sensor Circuit Intermittent", "Critical"),
        "P0719" to DTCInfo("Torque Converter/Brake Switch B Circuit Low", "Important"),
        "P0720" to DTCInfo("Output Speed Sensor Circuit", "Critical"),
        "P0721" to DTCInfo("Output Speed Sensor Circuit Range/Performance", "Critical"),
        "P0722" to DTCInfo("Output Speed Sensor Circuit No Signal", "Critical"),
        "P0723" to DTCInfo("Output Speed Sensor Circuit Intermittent", "Critical"),
        "P0724" to DTCInfo("Torque Converter/Brake Switch B Circuit High", "Important"),
        "P0725" to DTCInfo("Engine Speed Input Circuit", "Critical"),
        "P0726" to DTCInfo("Engine Speed Input Circuit Range/Performance", "Critical"),
        "P0727" to DTCInfo("Engine Speed Input Circuit No Signal", "Critical"),
        "P0728" to DTCInfo("Engine Speed Input Circuit Intermittent", "Critical"),
        "P0729" to DTCInfo("Gear 6 Incorrect Ratio", "Critical"),
        "P0730" to DTCInfo("Incorrect Gear Ratio", "Critical"),
        "P0731" to DTCInfo("Gear 1 Incorrect Ratio", "Critical"),
        "P0732" to DTCInfo("Gear 2 Incorrect Ratio", "Critical"),
        "P0733" to DTCInfo("Gear 3 Incorrect Ratio", "Critical"),
        "P0734" to DTCInfo("Gear 4 Incorrect Ratio", "Critical"),
        "P0735" to DTCInfo("Gear 5 Incorrect Ratio", "Critical"),
        "P0736" to DTCInfo("Reverse Incorrect Ratio", "Critical"),
        "P0737" to DTCInfo("TCM Engine Speed Output Circuit", "Important"),
        "P0738" to DTCInfo("TCM Engine Speed Output Circuit Low", "Important"),
        "P0739" to DTCInfo("TCM Engine Speed Output Circuit High", "Important"),
        "P0740" to DTCInfo("Torque Converter Clutch Circuit", "Important"),
        "P0741" to DTCInfo("Torque Converter Clutch Circuit Performance or Stuck Off", "Important"),
        "P0742" to DTCInfo("Torque Converter Clutch Circuit Stuck On", "Important"),
        "P0743" to DTCInfo("Torque Converter Clutch Circuit Electrical", "Important"),
        "P0744" to DTCInfo("Torque Converter Clutch Circuit Intermittent", "Important"),
        "P0745" to DTCInfo("Pressure Control Solenoid A", "Critical"),
        "P0746" to DTCInfo("Pressure Control Solenoid A Performance or Stuck Off", "Critical"),
        "P0747" to DTCInfo("Pressure Control Solenoid A Stuck On", "Critical"),
        "P0748" to DTCInfo("Pressure Control Solenoid A Electrical", "Critical"),
        "P0749" to DTCInfo("Pressure Control Solenoid A Intermittent", "Critical"),
        "P0750" to DTCInfo("Shift Solenoid A", "Critical"),
        "P0751" to DTCInfo("Shift Solenoid A Performance or Stuck Off", "Critical"),
        "P0752" to DTCInfo("Shift Solenoid A Stuck On", "Critical"),
        "P0753" to DTCInfo("Shift Solenoid A Electrical", "Critical"),
        "P0754" to DTCInfo("Shift Solenoid A Intermittent", "Critical"),
        "P0755" to DTCInfo("Shift Solenoid B", "Critical"),
        "P0756" to DTCInfo("Shift Solenoid B Performance or Stuck Off", "Critical"),
        "P0757" to DTCInfo("Shift Solenoid B Stuck On", "Critical"),
        "P0758" to DTCInfo("Shift Solenoid B Electrical", "Critical"),
        "P0759" to DTCInfo("Shift Solenoid B Intermittent", "Critical"),
        "P0760" to DTCInfo("Shift Solenoid C", "Critical"),
        "P0761" to DTCInfo("Shift Solenoid C Performance or Stuck Off", "Critical"),
        "P0762" to DTCInfo("Shift Solenoid C Stuck On", "Critical"),
        "P0763" to DTCInfo("Shift Solenoid C Electrical", "Critical"),
        "P0764" to DTCInfo("Shift Solenoid C Intermittent", "Critical"),
        "P0765" to DTCInfo("Shift Solenoid D", "Critical"),
        "P0766" to DTCInfo("Shift Solenoid D Performance or Stuck Off", "Critical"),
        "P0767" to DTCInfo("Shift Solenoid D Stuck On", "Critical"),
        "P0768" to DTCInfo("Shift Solenoid D Electrical", "Critical"),
        "P0769" to DTCInfo("Shift Solenoid D Intermittent", "Critical"),
        "P0770" to DTCInfo("Shift Solenoid E", "Critical"),
        "P0771" to DTCInfo("Shift Solenoid E Performance or Stuck Off", "Critical"),
        "P0772" to DTCInfo("Shift Solenoid E Stuck On", "Critical"),
        "P0773" to DTCInfo("Shift Solenoid E Electrical", "Critical"),
        "P0774" to DTCInfo("Shift Solenoid E Intermittent", "Critical"),
        "P0775" to DTCInfo("Pressure Control Solenoid B", "Critical"),
        "P0776" to DTCInfo("Pressure Control Solenoid B Performance or Stuck Off", "Critical"),
        "P0777" to DTCInfo("Pressure Control Solenoid B Stuck On", "Critical"),
        "P0778" to DTCInfo("Pressure Control Solenoid B Electrical", "Critical"),
        "P0779" to DTCInfo("Pressure Control Solenoid B Intermittent", "Critical"),
        "P0780" to DTCInfo("Shift Error", "Critical"),
        "P0781" to DTCInfo("1-2 Shift", "Critical"),
        "P0782" to DTCInfo("2-3 Shift", "Critical"),
        "P0783" to DTCInfo("3-4 Shift", "Critical"),
        "P0784" to DTCInfo("4-5 Shift", "Critical"),
        "P0785" to DTCInfo("Shift/Timing Solenoid", "Critical"),
        "P0786" to DTCInfo("Shift/Timing Solenoid Range/Performance", "Critical"),
        "P0787" to DTCInfo("Shift/Timing Solenoid Low", "Critical"),
        "P0788" to DTCInfo("Shift/Timing Solenoid High", "Critical"),
        "P0789" to DTCInfo("Shift/Timing Solenoid Intermittent", "Critical"),
        "P0790" to DTCInfo("Normal/Performance Switch Circuit", "Non-Critical"),
        "P0791" to DTCInfo("Intermediate Shaft Speed Sensor Circuit", "Important"),
        "P0792" to DTCInfo("Intermediate Shaft Speed Sensor Circuit Range/Performance", "Important"),
        "P0793" to DTCInfo("Intermediate Shaft Speed Sensor Circuit No Signal", "Important"),
        "P0794" to DTCInfo("Intermediate Shaft Speed Sensor Circuit Intermittent", "Important"),
        "P0795" to DTCInfo("Pressure Control Solenoid C", "Critical"),
        "P0796" to DTCInfo("Pressure Control Solenoid C Performance or Stuck Off", "Critical"),
        "P0797" to DTCInfo("Pressure Control Solenoid C Stuck On", "Critical"),
        "P0798" to DTCInfo("Pressure Control Solenoid C Electrical", "Critical"),
        "P0799" to DTCInfo("Pressure Control Solenoid C Intermittent", "Critical")
    )
}
