package com.wisedrive.obd2.constants

/**
 * DTC Descriptions - Body (B), Chassis (C), and Network (U) codes
 */
object DTCDescriptionsBCU {
    
    // Body Codes (B0xxx - B3xxx)
    val B_CODES: Map<String, DTCInfo> = mapOf(
        // B0xxx - Body General
        "B0001" to DTCInfo("Driver Frontal Deployment Control (Single Stage or Stage 1)", "Critical"),
        "B0002" to DTCInfo("Driver Frontal Deployment Control Stage 2", "Critical"),
        "B0003" to DTCInfo("Driver Frontal Deployment Control Stage 3", "Critical"),
        "B0004" to DTCInfo("Passenger Frontal Deployment Control (Single Stage or Stage 1)", "Critical"),
        "B0005" to DTCInfo("Passenger Frontal Deployment Control Stage 2", "Critical"),
        "B0006" to DTCInfo("Passenger Frontal Deployment Control Stage 3", "Critical"),
        "B0007" to DTCInfo("Driver Side Frontal Deployment Control (Single Stage or Stage 1)", "Critical"),
        "B0008" to DTCInfo("Driver Side Frontal Deployment Control Stage 2", "Critical"),
        "B0009" to DTCInfo("Passenger Side Frontal Deployment Control (Single Stage or Stage 1)", "Critical"),
        "B0010" to DTCInfo("Passenger Side Frontal Deployment Control Stage 2", "Critical"),
        "B0011" to DTCInfo("Driver Knee Bolster Deployment Control", "Critical"),
        "B0012" to DTCInfo("Passenger Knee Bolster Deployment Control", "Critical"),
        "B0013" to DTCInfo("Driver Seat Belt Pretensioner Deployment Control", "Critical"),
        "B0014" to DTCInfo("Passenger Seat Belt Pretensioner Deployment Control", "Critical"),
        "B0015" to DTCInfo("Driver Roof Rail Deployment Control", "Critical"),
        "B0016" to DTCInfo("Passenger Roof Rail Deployment Control", "Critical"),
        "B0017" to DTCInfo("Rear Side Thorax/Pelvis Deployment Control - Left", "Critical"),
        "B0018" to DTCInfo("Rear Side Thorax/Pelvis Deployment Control - Right", "Critical"),
        "B0020" to DTCInfo("Roof Rail Left Deployment Control", "Critical"),
        "B0021" to DTCInfo("Roof Rail Right Deployment Control", "Critical"),
        "B0022" to DTCInfo("Battery Low Voltage", "Important"),
        "B0023" to DTCInfo("Battery High Voltage", "Important"),
        "B0024" to DTCInfo("Ignition Input Circuit", "Important"),
        "B0025" to DTCInfo("Ignition Input Circuit Short to Ground", "Important"),
        "B0026" to DTCInfo("Ignition Input Circuit Short to Battery", "Important"),
        "B0028" to DTCInfo("Driver Frontal Squib 1 Circuit", "Critical"),
        "B0029" to DTCInfo("Passenger Frontal Squib 1 Circuit", "Critical"),
        "B0030" to DTCInfo("Driver Side Air Bag Squib Circuit", "Critical"),
        "B0031" to DTCInfo("Passenger Side Air Bag Squib Circuit", "Critical"),
        "B0032" to DTCInfo("Driver Seat Belt Pretensioner Squib Circuit", "Critical"),
        "B0033" to DTCInfo("Passenger Seat Belt Pretensioner Squib Circuit", "Critical"),
        "B0050" to DTCInfo("Front Impact Sensor 1", "Critical"),
        "B0051" to DTCInfo("Front Impact Sensor 2", "Critical"),
        "B0053" to DTCInfo("Side Impact Sensor - Left Front", "Critical"),
        "B0054" to DTCInfo("Side Impact Sensor - Right Front", "Critical"),
        "B0055" to DTCInfo("Side Impact Sensor - Left Rear", "Critical"),
        "B0056" to DTCInfo("Side Impact Sensor - Right Rear", "Critical"),
        "B0057" to DTCInfo("Center Impact Sensor", "Critical"),
        "B0071" to DTCInfo("Left Front Speaker Circuit Short to Ground", "Non-Critical"),
        "B0072" to DTCInfo("Left Front Speaker Circuit Short to Battery", "Non-Critical"),
        "B0073" to DTCInfo("Left Front Speaker Circuit Open", "Non-Critical"),
        "B0074" to DTCInfo("Right Front Speaker Circuit Short to Ground", "Non-Critical"),
        "B0075" to DTCInfo("Right Front Speaker Circuit Short to Battery", "Non-Critical"),
        "B0076" to DTCInfo("Right Front Speaker Circuit Open", "Non-Critical"),
        "B0077" to DTCInfo("Left Rear Speaker Circuit Short to Ground", "Non-Critical"),
        "B0078" to DTCInfo("Left Rear Speaker Circuit Short to Battery", "Non-Critical"),
        "B0079" to DTCInfo("Left Rear Speaker Circuit Open", "Non-Critical"),
        "B0080" to DTCInfo("Right Rear Speaker Circuit Short to Ground", "Non-Critical"),
        "B0081" to DTCInfo("Right Rear Speaker Circuit Short to Battery", "Non-Critical"),
        "B0082" to DTCInfo("Right Rear Speaker Circuit Open", "Non-Critical"),
        "B0100" to DTCInfo("Electronic Frontal Sensor 1", "Critical"),
        "B0101" to DTCInfo("Electronic Frontal Sensor 2", "Critical"),
        "B0102" to DTCInfo("Electronic Frontal Sensor 3", "Critical"),
        "B0103" to DTCInfo("Electronic Side Sensor - Left Front", "Critical"),
        "B0104" to DTCInfo("Electronic Side Sensor - Right Front", "Critical"),
        "B0105" to DTCInfo("Electronic Side Sensor - Left Rear", "Critical"),
        "B0106" to DTCInfo("Electronic Side Sensor - Right Rear", "Critical"),
        
        // B1xxx - Body Area Network
        "B1000" to DTCInfo("ECU Malfunction", "Critical"),
        "B1001" to DTCInfo("Option Configuration Error", "Important"),
        "B1004" to DTCInfo("Ignition Key-In Circuit Short to Ground", "Non-Critical"),
        "B1015" to DTCInfo("Battery Voltage High", "Important"),
        "B1016" to DTCInfo("Battery Voltage Low", "Important"),
        "B1200" to DTCInfo("Climate Control Push Button Circuit", "Non-Critical"),
        "B1201" to DTCInfo("Fuel Sender Circuit Failure", "Non-Critical"),
        "B1202" to DTCInfo("Fuel Sender Circuit Open", "Non-Critical"),
        "B1203" to DTCInfo("Fuel Sender Circuit Short To Ground", "Non-Critical"),
        "B1204" to DTCInfo("Fuel Sender Circuit Short To Battery", "Non-Critical"),
        "B1213" to DTCInfo("Anti-Theft Number Of Programmed Keys Is Below Minimum", "Important"),
        "B1232" to DTCInfo("Antenna Not Connected", "Non-Critical"),
        "B1318" to DTCInfo("Battery Voltage Low", "Important"),
        "B1342" to DTCInfo("ECU Is Defective", "Critical"),
        "B1352" to DTCInfo("Ignition Key-In Circuit Short To Battery", "Non-Critical"),
        "B1359" to DTCInfo("Ignition Run/Acc Circuit", "Important"),
        "B1600" to DTCInfo("PATS Received Incorrect Key Code From Ignition Key Transponder", "Important"),
        "B1601" to DTCInfo("Driver Seat Lumbar Support", "Non-Critical"),
        "B1602" to DTCInfo("Passenger Seat Position", "Non-Critical"),
        "B1603" to DTCInfo("Memory Set Switch Circuit Failure", "Non-Critical"),
        "B1604" to DTCInfo("Memory 1 Switch Circuit Failure", "Non-Critical"),
        "B1605" to DTCInfo("Memory 2 Switch Circuit Failure", "Non-Critical"),
        "B1606" to DTCInfo("Driver Mirror Assembly", "Non-Critical"),
        "B1607" to DTCInfo("Driver Mirror Horizontal Position", "Non-Critical"),
        "B1608" to DTCInfo("Driver Mirror Vertical Position", "Non-Critical"),
        "B1609" to DTCInfo("Passenger Mirror Assembly", "Non-Critical"),
        "B1610" to DTCInfo("Passenger Mirror Horizontal Position", "Non-Critical"),
        "B1611" to DTCInfo("Passenger Mirror Vertical Position", "Non-Critical"),
        "B1681" to DTCInfo("PATS Transceiver Module Signal Not Received", "Important"),
        "B1682" to DTCInfo("PATS Received Invalid Data From ECU", "Important"),
        "B1683" to DTCInfo("Body Control Module Communication Error", "Important"),
        
        // B2xxx - Body Systems
        "B2100" to DTCInfo("Head Lamp Out - Left", "Non-Critical"),
        "B2101" to DTCInfo("Head Lamp Out - Right", "Non-Critical"),
        "B2102" to DTCInfo("Fog Lamp Out - Front Left", "Non-Critical"),
        "B2103" to DTCInfo("Fog Lamp Out - Front Right", "Non-Critical"),
        "B2104" to DTCInfo("Turn Signal Lamp Out - Front Left", "Non-Critical"),
        "B2105" to DTCInfo("Turn Signal Lamp Out - Front Right", "Non-Critical"),
        "B2106" to DTCInfo("Turn Signal Lamp Out - Rear Left", "Non-Critical"),
        "B2107" to DTCInfo("Turn Signal Lamp Out - Rear Right", "Non-Critical"),
        "B2108" to DTCInfo("Brake Lamp Out - Left", "Important"),
        "B2109" to DTCInfo("Brake Lamp Out - Right", "Important"),
        "B2110" to DTCInfo("Tail Lamp Out - Left", "Non-Critical"),
        "B2111" to DTCInfo("Tail Lamp Out - Right", "Non-Critical"),
        "B2200" to DTCInfo("Heated Seat Module Open", "Non-Critical"),
        "B2201" to DTCInfo("Heated Seat Module Short To Ground", "Non-Critical"),
        "B2202" to DTCInfo("Heated Seat Module Short To Battery", "Non-Critical"),
        "B2600" to DTCInfo("Courtesy Lamp Circuit Open", "Non-Critical"),
        "B2601" to DTCInfo("Courtesy Lamp Circuit Short To Ground", "Non-Critical"),
        "B2602" to DTCInfo("Courtesy Lamp Circuit Short To Battery", "Non-Critical"),
        "B2900" to DTCInfo("Wiper Motor Front Circuit", "Non-Critical"),
        "B2901" to DTCInfo("Wiper Motor Rear Circuit", "Non-Critical"),
        "B2902" to DTCInfo("Wiper Relay Circuit Open", "Non-Critical"),
        "B2903" to DTCInfo("Wiper Relay Circuit Short To Ground", "Non-Critical"),
        "B2904" to DTCInfo("Wiper Relay Circuit Short To Battery", "Non-Critical"),
        "B2950" to DTCInfo("Central Locking Motor - Driver Door", "Non-Critical"),
        "B2951" to DTCInfo("Central Locking Motor - Passenger Door", "Non-Critical"),
        "B2952" to DTCInfo("Central Locking Motor - Rear Left Door", "Non-Critical"),
        "B2953" to DTCInfo("Central Locking Motor - Rear Right Door", "Non-Critical"),
        "B2954" to DTCInfo("Central Locking Motor - Tailgate/Trunk", "Non-Critical")
    )

    // Chassis Codes (C0xxx - C3xxx)
    val C_CODES: Map<String, DTCInfo> = mapOf(
        // C0xxx - Chassis General
        "C0000" to DTCInfo("Vehicle Speed Information Circuit", "Important"),
        "C0010" to DTCInfo("Left Front Wheel Speed Circuit", "Critical"),
        "C0011" to DTCInfo("Left Front Wheel Speed Circuit Range/Performance", "Critical"),
        "C0012" to DTCInfo("Left Front Wheel Speed Circuit Short to Ground", "Critical"),
        "C0013" to DTCInfo("Left Front Wheel Speed Circuit Open", "Critical"),
        "C0020" to DTCInfo("Right Front Wheel Speed Circuit", "Critical"),
        "C0021" to DTCInfo("Right Front Wheel Speed Circuit Range/Performance", "Critical"),
        "C0022" to DTCInfo("Right Front Wheel Speed Circuit Short to Ground", "Critical"),
        "C0023" to DTCInfo("Right Front Wheel Speed Circuit Open", "Critical"),
        "C0030" to DTCInfo("Left Rear Wheel Speed Circuit", "Critical"),
        "C0031" to DTCInfo("Left Rear Wheel Speed Circuit Range/Performance", "Critical"),
        "C0032" to DTCInfo("Left Rear Wheel Speed Circuit Short to Ground", "Critical"),
        "C0033" to DTCInfo("Left Rear Wheel Speed Circuit Open", "Critical"),
        "C0035" to DTCInfo("Left Front Wheel Speed Sensor Circuit", "Critical"),
        "C0040" to DTCInfo("Right Front Wheel Speed Sensor Circuit", "Critical"),
        "C0041" to DTCInfo("Right Rear Wheel Speed Circuit Range/Performance", "Critical"),
        "C0042" to DTCInfo("Right Rear Wheel Speed Circuit Short to Ground", "Critical"),
        "C0043" to DTCInfo("Right Rear Wheel Speed Circuit Open", "Critical"),
        "C0045" to DTCInfo("Left Rear Wheel Speed Sensor Circuit", "Critical"),
        "C0050" to DTCInfo("Right Rear Wheel Speed Sensor Circuit", "Critical"),
        "C0051" to DTCInfo("LF Wheel Speed Sensor Signal Missing", "Critical"),
        "C0052" to DTCInfo("RF Wheel Speed Sensor Signal Missing", "Critical"),
        "C0053" to DTCInfo("LR Wheel Speed Sensor Signal Missing", "Critical"),
        "C0054" to DTCInfo("RR Wheel Speed Sensor Signal Missing", "Critical"),
        "C0060" to DTCInfo("Left Front ABS Solenoid 1 Circuit", "Critical"),
        "C0061" to DTCInfo("Left Front ABS Solenoid 2 Circuit", "Critical"),
        "C0062" to DTCInfo("Right Front ABS Solenoid 1 Circuit", "Critical"),
        "C0063" to DTCInfo("Right Front ABS Solenoid 2 Circuit", "Critical"),
        "C0064" to DTCInfo("Left Rear ABS Solenoid 1 Circuit", "Critical"),
        "C0065" to DTCInfo("Left Rear ABS Solenoid 2 Circuit", "Critical"),
        "C0066" to DTCInfo("Right Rear ABS Solenoid 1 Circuit", "Critical"),
        "C0067" to DTCInfo("Right Rear ABS Solenoid 2 Circuit", "Critical"),
        "C0070" to DTCInfo("ABS Pump Motor Circuit", "Critical"),
        "C0071" to DTCInfo("ABS Pump Motor Circuit Low", "Critical"),
        "C0072" to DTCInfo("ABS Pump Motor Circuit High", "Critical"),
        "C0073" to DTCInfo("ABS Pump Motor Circuit Open", "Critical"),
        "C0080" to DTCInfo("ABS Brake Switch Circuit", "Important"),
        "C0081" to DTCInfo("Brake Switch Circuit 2", "Important"),
        "C0100" to DTCInfo("Electronic Suspension Control Module", "Important"),
        "C0110" to DTCInfo("Pump Motor Circuit", "Important"),
        "C0121" to DTCInfo("Valve Relay Circuit", "Important"),
        "C0128" to DTCInfo("Low Brake Fluid Circuit Low", "Critical"),
        "C0131" to DTCInfo("ABS/TCS Brake Pressure Circuit Range/Performance", "Critical"),
        "C0136" to DTCInfo("Base Brake System Pressure Circuit Low", "Critical"),
        "C0141" to DTCInfo("Left Front ABS Channel in Release Too Long", "Critical"),
        "C0146" to DTCInfo("Right Front ABS Channel in Release Too Long", "Critical"),
        "C0151" to DTCInfo("Left Rear ABS Channel in Release Too Long", "Critical"),
        "C0156" to DTCInfo("Right Rear ABS Channel in Release Too Long", "Critical"),
        "C0161" to DTCInfo("ABS/TCS Brake Switch Circuit", "Important"),
        "C0186" to DTCInfo("Lateral Accelerometer Circuit", "Important"),
        "C0196" to DTCInfo("Yaw Rate Circuit", "Important"),
        "C0221" to DTCInfo("Right Front Wheel Speed Sensor Circuit Open", "Critical"),
        "C0222" to DTCInfo("Right Front Wheel Speed Signal Missing", "Critical"),
        "C0223" to DTCInfo("Right Front Wheel Speed Signal Erratic", "Critical"),
        "C0225" to DTCInfo("Left Front Wheel Speed Sensor Circuit Open", "Critical"),
        "C0226" to DTCInfo("Left Front Wheel Speed Signal Missing", "Critical"),
        "C0227" to DTCInfo("Left Front Wheel Speed Signal Erratic", "Critical"),
        "C0229" to DTCInfo("Drop Out of Front Wheel Speed Signals", "Critical"),
        "C0235" to DTCInfo("Rear Wheel Speed Signal Circuit Open", "Critical"),
        "C0236" to DTCInfo("Rear Wheel Speed Signal Circuit Short to Ground", "Critical"),
        "C0237" to DTCInfo("Rear Wheel Speed Signal Erratic", "Critical"),
        "C0238" to DTCInfo("Wheel Speed Mismatch", "Important"),
        "C0240" to DTCInfo("EBCM Control Valve Circuit", "Critical"),
        "C0241" to DTCInfo("EBCM Control Valve Circuit Open", "Critical"),
        "C0244" to DTCInfo("Pulse Width Modulated Delivered Torque Circuit Low", "Important"),
        "C0245" to DTCInfo("Wheel Speed Sensor Frequency Error", "Important"),
        "C0252" to DTCInfo("Active Brake Control Sensors Uncorrelated", "Important"),
        "C0265" to DTCInfo("EBCM Motor Relay Circuit", "Critical"),
        "C0267" to DTCInfo("Pump Motor Circuit Open/Shorted", "Critical"),
        "C0268" to DTCInfo("Pump Motor Circuit Shorted to Ground", "Critical"),
        "C0269" to DTCInfo("Excessive Dump/Isolation Time", "Important"),
        "C0271" to DTCInfo("EBCM/EBTCM Communication Error", "Critical"),
        "C0272" to DTCInfo("EBCM Calibration Mismatch", "Important"),
        "C0281" to DTCInfo("Brake Switch Circuit", "Important"),
        "C0283" to DTCInfo("Traction Switch Shorted to Ground", "Non-Critical"),
        "C0284" to DTCInfo("EBCM Loop Malfunction", "Critical"),
        "C0287" to DTCInfo("Delivered Torque Signal Circuit", "Important"),
        "C0290" to DTCInfo("Lost Communications With PCM", "Critical"),
        "C0291" to DTCInfo("Lost Communications With BCM", "Important"),
        "C0292" to DTCInfo("Lost Communications With IPC/DIC", "Non-Critical"),
        "C0297" to DTCInfo("Power train Configuration Not Valid", "Important"),
        "C0298" to DTCInfo("Power train Indicated Traction Control", "Important"),
        "C0300" to DTCInfo("Rear Speed Sensor Malfunction", "Critical"),
        "C0305" to DTCInfo("Front Speed Sensor Malfunction", "Critical"),
        "C0321" to DTCInfo("Transfer Case Lock Motor Circuit", "Important"),
        "C0327" to DTCInfo("Encoder Circuit", "Important"),
        "C0359" to DTCInfo("Four Wheel Drive Low Range Circuit", "Non-Critical"),
        "C0387" to DTCInfo("Device Ignition Supply Voltage", "Important"),
        "C0460" to DTCInfo("Steering Position Sensor Circuit", "Important"),
        "C0461" to DTCInfo("Steering Angle Sensor Circuit Range/Performance", "Important"),
        "C0472" to DTCInfo("Steering Wheel Speed Sensor Signal V Low", "Important"),
        "C0473" to DTCInfo("Steering Wheel Speed Sensor Signal V High", "Important"),
        "C0495" to DTCInfo("EVO Tracking Error", "Important"),
        "C0498" to DTCInfo("Steering Assist Control Module Sensor Circuit", "Important"),
        "C0550" to DTCInfo("ECU Performance", "Critical"),
        "C0561" to DTCInfo("System Disabled", "Critical"),
        "C0563" to DTCInfo("Calibration Data Not Programmed", "Critical"),
        "C0577" to DTCInfo("Left Front Solenoid Circuit Low", "Critical"),
        "C0578" to DTCInfo("Left Front Solenoid Circuit High", "Critical"),
        "C0579" to DTCInfo("Left Front Solenoid Circuit Open", "Critical"),
        "C0582" to DTCInfo("Right Front Solenoid Circuit Low", "Critical"),
        "C0583" to DTCInfo("Right Front Solenoid Circuit High", "Critical"),
        "C0584" to DTCInfo("Right Front Solenoid Circuit Open", "Critical"),
        "C0587" to DTCInfo("Left Rear Solenoid Circuit Low", "Critical"),
        "C0588" to DTCInfo("Left Rear Solenoid Circuit High", "Critical"),
        "C0589" to DTCInfo("Left Rear Solenoid Circuit Open", "Critical"),
        "C0592" to DTCInfo("Right Rear Solenoid Circuit Low", "Critical"),
        "C0593" to DTCInfo("Right Rear Solenoid Circuit High", "Critical"),
        "C0594" to DTCInfo("Right Rear Solenoid Circuit Open", "Critical"),
        "C0611" to DTCInfo("VIN Information Error", "Important"),
        "C0620" to DTCInfo("Transmission Communications Malfunction", "Important"),
        "C0635" to DTCInfo("Left Front Normal Force Circuit Malfunction", "Important"),
        "C0636" to DTCInfo("Left Front Normal Force Circuit Range/Performance", "Important"),
        "C0638" to DTCInfo("Right Front Normal Force Circuit Malfunction", "Important"),
        "C0640" to DTCInfo("Right Front Normal Force Circuit Range/Performance", "Important"),
        "C0657" to DTCInfo("Level Control Compressor Relay Malfunction", "Important"),
        "C0660" to DTCInfo("Level Control Exhaust Valve Solenoid Circuit Malfunction", "Important"),
        "C0662" to DTCInfo("Level Control Compressor Relay Short to Ground", "Important"),
        "C0663" to DTCInfo("Level Control Compressor Relay Short to Battery", "Important"),
        "C0665" to DTCInfo("Chassis Pitch Signal Circuit", "Important"),
        "C0690" to DTCInfo("Damper Solenoid Circuit Malfunction", "Important"),
        "C0691" to DTCInfo("Damper Solenoid Circuit Range/Performance", "Important"),
        "C0710" to DTCInfo("Steering Position Signal", "Important"),
        "C0750" to DTCInfo("Tire Pressure Monitor System Sensor Not Transmitting", "Non-Critical"),
        "C0755" to DTCInfo("Tire Pressure Sensor RF ID Not Recognized", "Non-Critical"),
        "C0760" to DTCInfo("Tire Pressure Sensor LF ID Not Recognized", "Non-Critical"),
        "C0765" to DTCInfo("Tire Pressure Sensor RR ID Not Recognized", "Non-Critical"),
        "C0770" to DTCInfo("Tire Pressure Sensor LR ID Not Recognized", "Non-Critical"),
        "C0775" to DTCInfo("Tire Pressure Sensor Spare ID Not Recognized", "Non-Critical"),
        "C0800" to DTCInfo("Device Power Circuit", "Important"),
        "C0896" to DTCInfo("Device Voltage Range/Performance", "Important"),
        "C0899" to DTCInfo("Device Voltage Low", "Important"),
        "C0900" to DTCInfo("Device Voltage High", "Important")
    )

    // Network/Communication Codes (U0xxx - U3xxx)
    val U_CODES: Map<String, DTCInfo> = mapOf(
        // U0xxx - Network Communication
        "U0001" to DTCInfo("High Speed CAN Communication Bus", "Critical"),
        "U0002" to DTCInfo("High Speed CAN Communication Bus Performance", "Critical"),
        "U0003" to DTCInfo("High Speed CAN Communication Bus (+) Open", "Critical"),
        "U0004" to DTCInfo("High Speed CAN Communication Bus (+) Low", "Critical"),
        "U0005" to DTCInfo("High Speed CAN Communication Bus (+) High", "Critical"),
        "U0006" to DTCInfo("High Speed CAN Communication Bus (-) Open", "Critical"),
        "U0007" to DTCInfo("High Speed CAN Communication Bus (-) Low", "Critical"),
        "U0008" to DTCInfo("High Speed CAN Communication Bus (-) High", "Critical"),
        "U0009" to DTCInfo("High Speed CAN Communication Bus (-) Shorted to Bus (+)", "Critical"),
        "U0010" to DTCInfo("Medium Speed CAN Communication Bus", "Critical"),
        "U0011" to DTCInfo("Medium Speed CAN Communication Bus Performance", "Critical"),
        "U0012" to DTCInfo("Medium Speed CAN Communication Bus (+) Open", "Critical"),
        "U0013" to DTCInfo("Medium Speed CAN Communication Bus (+) Low", "Critical"),
        "U0014" to DTCInfo("Medium Speed CAN Communication Bus (+) High", "Critical"),
        "U0015" to DTCInfo("Medium Speed CAN Communication Bus (-) Open", "Critical"),
        "U0016" to DTCInfo("Medium Speed CAN Communication Bus (-) Low", "Critical"),
        "U0017" to DTCInfo("Medium Speed CAN Communication Bus (-) High", "Critical"),
        "U0018" to DTCInfo("Medium Speed CAN Communication Bus (-) Shorted to Bus (+)", "Critical"),
        "U0019" to DTCInfo("Low Speed CAN Communication Bus", "Important"),
        "U0020" to DTCInfo("Low Speed CAN Communication Bus Performance", "Important"),
        "U0026" to DTCInfo("Vehicle Communication Bus A Performance", "Important"),
        "U0027" to DTCInfo("Vehicle Communication Bus B Performance", "Important"),
        "U0028" to DTCInfo("Vehicle Communication Bus C Performance", "Important"),
        "U0029" to DTCInfo("Vehicle Communication Bus D Performance", "Important"),
        "U0073" to DTCInfo("Control Module Communication Bus Off", "Critical"),
        "U0100" to DTCInfo("Lost Communication with ECM/PCM A", "Critical"),
        "U0101" to DTCInfo("Lost Communication with TCM", "Critical"),
        "U0102" to DTCInfo("Lost Communication with Transfer Case Control Module", "Important"),
        "U0103" to DTCInfo("Lost Communication with Gear Shift Module", "Important"),
        "U0104" to DTCInfo("Lost Communication with Cruise Control Module", "Non-Critical"),
        "U0105" to DTCInfo("Lost Communication with Fuel Injector Control Module", "Critical"),
        "U0106" to DTCInfo("Lost Communication with Glow Plug Control Module", "Important"),
        "U0107" to DTCInfo("Lost Communication with Throttle Actuator Control Module", "Critical"),
        "U0108" to DTCInfo("Lost Communication with Alternative Fuel Control Module", "Important"),
        "U0109" to DTCInfo("Lost Communication with Fuel Pump Control Module", "Critical"),
        "U0110" to DTCInfo("Lost Communication with Drive Motor Control Module", "Critical"),
        "U0111" to DTCInfo("Lost Communication with Battery Energy Control Module A", "Important"),
        "U0112" to DTCInfo("Lost Communication with Battery Energy Control Module B", "Important"),
        "U0113" to DTCInfo("Lost Communication with Emissions Critical Control Information", "Important"),
        "U0114" to DTCInfo("Lost Communication with Four-Wheel Drive Clutch Control Module", "Important"),
        "U0115" to DTCInfo("Lost Communication with ECM/PCM B", "Critical"),
        "U0116" to DTCInfo("Lost Communication with Vehicle Dynamics Control Module", "Important"),
        "U0117" to DTCInfo("Lost Communication with Transmission Range Sensor Module", "Important"),
        "U0118" to DTCInfo("Lost Communication with Transmission Drive Motor Control Module", "Important"),
        "U0119" to DTCInfo("Lost Communication with Chassis Control Module A", "Important"),
        "U0120" to DTCInfo("Lost Communication with Chassis Control Module B", "Important"),
        "U0121" to DTCInfo("Lost Communication with ABS Control Module", "Critical"),
        "U0122" to DTCInfo("Lost Communication with Vehicle Dynamics Control Module", "Important"),
        "U0123" to DTCInfo("Lost Communication with Yaw Rate Sensor Module", "Important"),
        "U0124" to DTCInfo("Lost Communication with Lateral Acceleration Sensor Module", "Important"),
        "U0125" to DTCInfo("Lost Communication with Multi-Axis Acceleration Sensor Module", "Important"),
        "U0126" to DTCInfo("Lost Communication with Steering Angle Sensor Module", "Important"),
        "U0127" to DTCInfo("Lost Communication with Tire Pressure Monitor Module", "Non-Critical"),
        "U0128" to DTCInfo("Lost Communication with Park Brake Control Module", "Important"),
        "U0129" to DTCInfo("Lost Communication with Brake System Control Module", "Critical"),
        "U0130" to DTCInfo("Lost Communication with Steering Effort Control Module", "Important"),
        "U0131" to DTCInfo("Lost Communication with Power Steering Control Module", "Important"),
        "U0132" to DTCInfo("Lost Communication with Ride Level Control Module", "Important"),
        "U0133" to DTCInfo("Lost Communication with Suspension Control Module A", "Important"),
        "U0134" to DTCInfo("Lost Communication with Suspension Control Module B", "Important"),
        "U0135" to DTCInfo("Lost Communication with Suspension Control Module C", "Important"),
        "U0136" to DTCInfo("Lost Communication with Suspension Control Module D", "Important"),
        "U0140" to DTCInfo("Lost Communication with Body Control Module", "Important"),
        "U0141" to DTCInfo("Lost Communication with Body Control Module A", "Important"),
        "U0142" to DTCInfo("Lost Communication with Body Control Module B", "Important"),
        "U0143" to DTCInfo("Lost Communication with Body Control Module C", "Important"),
        "U0144" to DTCInfo("Lost Communication with Body Control Module D", "Important"),
        "U0145" to DTCInfo("Lost Communication with Body Control Module E", "Important"),
        "U0146" to DTCInfo("Lost Communication with Gateway A", "Critical"),
        "U0147" to DTCInfo("Lost Communication with Gateway B", "Critical"),
        "U0148" to DTCInfo("Lost Communication with Gateway C", "Critical"),
        "U0149" to DTCInfo("Lost Communication with Gateway D", "Critical"),
        "U0150" to DTCInfo("Lost Communication with Gateway E", "Critical"),
        "U0151" to DTCInfo("Lost Communication with Restraints Control Module", "Critical"),
        "U0152" to DTCInfo("Lost Communication with Side Restraints Control Module - Left", "Critical"),
        "U0153" to DTCInfo("Lost Communication with Side Restraints Control Module - Right", "Critical"),
        "U0154" to DTCInfo("Lost Communication with Restraints Occupant Sensing Control Module", "Critical"),
        "U0155" to DTCInfo("Lost Communication with Instrument Panel Cluster", "Important"),
        "U0156" to DTCInfo("Lost Communication with Information Center A", "Non-Critical"),
        "U0157" to DTCInfo("Lost Communication with Information Center B", "Non-Critical"),
        "U0158" to DTCInfo("Lost Communication with Head Up Display", "Non-Critical"),
        "U0159" to DTCInfo("Lost Communication with Parking Assist Control Module", "Non-Critical"),
        "U0160" to DTCInfo("Lost Communication with Audible Alert Control Module", "Non-Critical"),
        "U0161" to DTCInfo("Lost Communication with Compass Module", "Non-Critical"),
        "U0162" to DTCInfo("Lost Communication with Navigation Display Module", "Non-Critical"),
        "U0163" to DTCInfo("Lost Communication with Navigation Control Module", "Non-Critical"),
        "U0164" to DTCInfo("Lost Communication with HVAC Control Module", "Non-Critical"),
        "U0165" to DTCInfo("Lost Communication with HVAC Control Module - Rear", "Non-Critical"),
        "U0166" to DTCInfo("Lost Communication with Auxiliary Heater Control Module", "Non-Critical"),
        "U0167" to DTCInfo("Lost Communication with Vehicle Immobilizer Control Module", "Critical"),
        "U0168" to DTCInfo("Lost Communication with Vehicle Security Control Module", "Important"),
        "U0169" to DTCInfo("Lost Communication with Sunroof Control Module", "Non-Critical"),
        "U0170" to DTCInfo("Lost Communication with Restraints System Sensor A", "Critical"),
        "U0171" to DTCInfo("Lost Communication with Restraints System Sensor B", "Critical"),
        "U0172" to DTCInfo("Lost Communication with Restraints System Sensor C", "Critical"),
        "U0173" to DTCInfo("Lost Communication with Restraints System Sensor D", "Critical"),
        "U0174" to DTCInfo("Lost Communication with Restraints System Sensor E", "Critical"),
        "U0175" to DTCInfo("Lost Communication with Restraints System Sensor F", "Critical"),
        "U0176" to DTCInfo("Lost Communication with Restraints System Sensor G", "Critical"),
        "U0177" to DTCInfo("Lost Communication with Restraints System Sensor H", "Critical"),
        "U0178" to DTCInfo("Lost Communication with Restraints System Sensor I", "Critical"),
        "U0179" to DTCInfo("Lost Communication with Restraints System Sensor J", "Critical"),
        "U0180" to DTCInfo("Lost Communication with Automatic Lighting Control Module", "Non-Critical"),
        "U0181" to DTCInfo("Lost Communication with Headlamp Leveling Control Module", "Non-Critical"),
        "U0182" to DTCInfo("Lost Communication with Lighting Control Module - Front", "Non-Critical"),
        "U0183" to DTCInfo("Lost Communication with Lighting Control Module - Rear", "Non-Critical"),
        "U0184" to DTCInfo("Lost Communication with Radio", "Non-Critical"),
        "U0185" to DTCInfo("Lost Communication with Antenna Control Module", "Non-Critical"),
        "U0186" to DTCInfo("Lost Communication with Audio Amplifier", "Non-Critical"),
        "U0187" to DTCInfo("Lost Communication with Digital Disc Player/Changer Module", "Non-Critical"),
        "U0188" to DTCInfo("Lost Communication with Digital Audio Receiver Module", "Non-Critical"),
        "U0189" to DTCInfo("Lost Communication with Digital Audio Receiver Module B", "Non-Critical"),
        "U0190" to DTCInfo("Lost Communication with Digital Audio Receiver Module C", "Non-Critical"),
        "U0191" to DTCInfo("Lost Communication with Television Module", "Non-Critical"),
        "U0192" to DTCInfo("Lost Communication with Personal Computer", "Non-Critical"),
        "U0193" to DTCInfo("Lost Communication with Digital Audio Input Module", "Non-Critical"),
        "U0194" to DTCInfo("Lost Communication with Emergency Call Module", "Important"),
        "U0195" to DTCInfo("Lost Communication with Telematic Control Module", "Non-Critical"),
        "U0196" to DTCInfo("Lost Communication with Cellular Telephone Module", "Non-Critical"),
        "U0197" to DTCInfo("Lost Communication with Hands Free Calling Module", "Non-Critical"),
        "U0198" to DTCInfo("Lost Communication with Integrated Radio Chassis Module", "Non-Critical"),
        "U0199" to DTCInfo("Lost Communication with Door Control Module A", "Non-Critical"),
        "U0200" to DTCInfo("Lost Communication with Door Control Module B", "Non-Critical"),
        "U0201" to DTCInfo("Lost Communication with Door Control Module C", "Non-Critical"),
        "U0202" to DTCInfo("Lost Communication with Door Control Module D", "Non-Critical"),
        "U0203" to DTCInfo("Lost Communication with Door Control Module E", "Non-Critical"),
        "U0204" to DTCInfo("Lost Communication with Door Control Module F", "Non-Critical"),
        "U0205" to DTCInfo("Lost Communication with Door Control Module G", "Non-Critical"),
        "U0206" to DTCInfo("Lost Communication with Folding Top Control Module", "Non-Critical"),
        "U0207" to DTCInfo("Lost Communication with Movable Roof Control Module", "Non-Critical"),
        "U0208" to DTCInfo("Lost Communication with Seat Control Module A", "Non-Critical"),
        "U0209" to DTCInfo("Lost Communication with Seat Control Module B", "Non-Critical"),
        "U0210" to DTCInfo("Lost Communication with Seat Control Module C", "Non-Critical"),
        "U0211" to DTCInfo("Lost Communication with Seat Control Module D", "Non-Critical"),
        "U0212" to DTCInfo("Lost Communication with Steering Column Control Module", "Important"),
        "U0213" to DTCInfo("Lost Communication with Mirror Control Module", "Non-Critical"),
        "U0214" to DTCInfo("Lost Communication with Remote Function Actuation", "Non-Critical"),
        "U0215" to DTCInfo("Lost Communication with Door Switch Module A", "Non-Critical"),
        "U0216" to DTCInfo("Lost Communication with Door Switch Module B", "Non-Critical"),
        "U0217" to DTCInfo("Lost Communication with Door Switch Module C", "Non-Critical"),
        "U0218" to DTCInfo("Lost Communication with Door Switch Module D", "Non-Critical"),
        "U0219" to DTCInfo("Lost Communication with Door Switch Module E", "Non-Critical"),
        "U0220" to DTCInfo("Lost Communication with Door Switch Module F", "Non-Critical"),
        "U0221" to DTCInfo("Lost Communication with Door Switch Module G", "Non-Critical"),
        "U0222" to DTCInfo("Lost Communication with Door Window Motor A", "Non-Critical"),
        "U0223" to DTCInfo("Lost Communication with Door Window Motor B", "Non-Critical"),
        "U0224" to DTCInfo("Lost Communication with Door Window Motor C", "Non-Critical"),
        "U0225" to DTCInfo("Lost Communication with Door Window Motor D", "Non-Critical"),
        "U0226" to DTCInfo("Lost Communication with Door Window Motor E", "Non-Critical"),
        "U0227" to DTCInfo("Lost Communication with Door Window Motor F", "Non-Critical"),
        "U0228" to DTCInfo("Lost Communication with Door Window Motor G", "Non-Critical"),
        "U0229" to DTCInfo("Lost Communication with Heated Steering Wheel Module", "Non-Critical"),
        "U0230" to DTCInfo("Lost Communication with Rear Gate Module", "Non-Critical"),
        "U0231" to DTCInfo("Lost Communication with Rain Sensing Module", "Non-Critical"),
        "U0232" to DTCInfo("Lost Communication with Side Obstacle Detection Control Module - Left", "Non-Critical"),
        "U0233" to DTCInfo("Lost Communication with Side Obstacle Detection Control Module - Right", "Non-Critical"),
        "U0234" to DTCInfo("Lost Communication with Convenience Recall Module", "Non-Critical"),
        "U0235" to DTCInfo("Lost Communication with Cruise Control Front Distance Range Sensor", "Non-Critical"),
        "U0300" to DTCInfo("Internal Control Module Software Incompatibility", "Important"),
        "U0301" to DTCInfo("Software Incompatibility with ECM/PCM", "Important"),
        "U0302" to DTCInfo("Software Incompatibility with TCM", "Important"),
        "U0303" to DTCInfo("Software Incompatibility with Transfer Case Control Module", "Important"),
        "U0304" to DTCInfo("Software Incompatibility with Gear Shift Control Module", "Non-Critical"),
        "U0305" to DTCInfo("Software Incompatibility with Cruise Control Module", "Non-Critical"),
        "U0400" to DTCInfo("Invalid Data Received", "Important"),
        "U0401" to DTCInfo("Invalid Data Received from ECM/PCM", "Critical"),
        "U0402" to DTCInfo("Invalid Data Received from TCM", "Critical"),
        "U0403" to DTCInfo("Invalid Data Received from Transfer Case Control Module", "Important"),
        "U0404" to DTCInfo("Invalid Data Received from Gear Shift Control Module", "Important"),
        "U0405" to DTCInfo("Invalid Data Received from Cruise Control Module", "Non-Critical"),
        "U0406" to DTCInfo("Invalid Data Received from Fuel Injector Control Module", "Important"),
        "U0407" to DTCInfo("Invalid Data Received from Glow Plug Control Module", "Important"),
        "U0408" to DTCInfo("Invalid Data Received from Throttle Actuator Control Module", "Critical"),
        "U0409" to DTCInfo("Invalid Data Received from Alternative Fuel Control Module", "Important"),
        "U0410" to DTCInfo("Invalid Data Received from Fuel Pump Control Module", "Important"),
        "U0411" to DTCInfo("Invalid Data Received from Drive Motor Control Module", "Important"),
        "U0412" to DTCInfo("Invalid Data Received from Battery Energy Control Module A", "Important"),
        "U0413" to DTCInfo("Invalid Data Received from Battery Energy Control Module B", "Important"),
        "U0414" to DTCInfo("Invalid Data Received from Emissions Critical Control Information", "Important"),
        "U0415" to DTCInfo("Invalid Data Received from ABS Control Module", "Critical"),
        "U0416" to DTCInfo("Invalid Data Received from Vehicle Dynamics Control Module", "Important"),
        "U0417" to DTCInfo("Invalid Data Received from Park Brake Control Module", "Important"),
        "U0418" to DTCInfo("Invalid Data Received from Brake System Control Module", "Critical"),
        "U0419" to DTCInfo("Invalid Data Received from Steering Effort Control Module", "Important"),
        "U0420" to DTCInfo("Invalid Data Received from Power Steering Control Module", "Important"),
        "U0421" to DTCInfo("Invalid Data Received from Ride Level Control Module", "Important"),
        "U0422" to DTCInfo("Invalid Data Received from Body Control Module", "Important"),
        "U0423" to DTCInfo("Invalid Data Received from Instrument Panel Cluster", "Non-Critical"),
        "U0424" to DTCInfo("Invalid Data Received from HVAC Control Module", "Non-Critical"),
        "U0425" to DTCInfo("Invalid Data Received from Auxiliary Heater Control Module", "Non-Critical"),
        "U0426" to DTCInfo("Invalid Data Received from Vehicle Immobilizer Control Module", "Critical"),
        "U0427" to DTCInfo("Invalid Data Received from Vehicle Security Control Module", "Important"),
        "U0428" to DTCInfo("Invalid Data Received from Steering Angle Sensor Module", "Important"),
        "U1000" to DTCInfo("Class 2 Communication Malfunction", "Important"),
        "U1016" to DTCInfo("Loss of Communication with ECU", "Important"),
        "U1026" to DTCInfo("Loss of GMLAN Communication", "Important"),
        "U1041" to DTCInfo("Lost Communication with Antilock Brake System Module", "Critical"),
        "U1064" to DTCInfo("Lost Communication with Body Control Module", "Important"),
        "U1096" to DTCInfo("Lost Communication with Electronic Suspension Control Module", "Important"),
        "U1097" to DTCInfo("Lost Communication with Instrument Panel Cluster", "Non-Critical"),
        "U1255" to DTCInfo("Generic Driveline Fault", "Important"),
        "U1301" to DTCInfo("High Speed GMLAN Message Timeout", "Important"),
        "U2000" to DTCInfo("Module Not Configured", "Important"),
        "U2001" to DTCInfo("Module Configuration Incomplete", "Important"),
        "U2100" to DTCInfo("Initial Value (Module Self-Test)", "Non-Critical"),
        "U3000" to DTCInfo("Control Module", "Important"),
        "U3001" to DTCInfo("Battery Voltage", "Important"),
        "U3002" to DTCInfo("Control Module - Internal Temperature", "Important"),
        "U3003" to DTCInfo("Control Module - Software", "Important")
    )
}
