package com.wisedrive.obd2.constants

/**
 * DTC Descriptions - Part 2: Powertrain P02xx-P03xx codes (Fuel/Air, Ignition, Emissions)
 */
object DTCDescriptionsP1 {
    
    val P02_CODES: Map<String, DTCInfo> = mapOf(
        // P02xx - Fuel and Air Metering (Injector Circuit)
        "P0200" to DTCInfo("Injector Circuit", "Critical"),
        "P0201" to DTCInfo("Injector Circuit - Cylinder 1", "Critical"),
        "P0202" to DTCInfo("Injector Circuit - Cylinder 2", "Critical"),
        "P0203" to DTCInfo("Injector Circuit - Cylinder 3", "Critical"),
        "P0204" to DTCInfo("Injector Circuit - Cylinder 4", "Critical"),
        "P0205" to DTCInfo("Injector Circuit - Cylinder 5", "Critical"),
        "P0206" to DTCInfo("Injector Circuit - Cylinder 6", "Critical"),
        "P0207" to DTCInfo("Injector Circuit - Cylinder 7", "Critical"),
        "P0208" to DTCInfo("Injector Circuit - Cylinder 8", "Critical"),
        "P0209" to DTCInfo("Injector Circuit - Cylinder 9", "Critical"),
        "P0210" to DTCInfo("Injector Circuit - Cylinder 10", "Critical"),
        "P0211" to DTCInfo("Injector Circuit - Cylinder 11", "Critical"),
        "P0212" to DTCInfo("Injector Circuit - Cylinder 12", "Critical"),
        "P0213" to DTCInfo("Cold Start Injector 1", "Important"),
        "P0214" to DTCInfo("Cold Start Injector 2", "Important"),
        "P0215" to DTCInfo("Engine Shutoff Solenoid", "Critical"),
        "P0216" to DTCInfo("Injection Timing Control Circuit", "Critical"),
        "P0217" to DTCInfo("Engine Coolant Over Temperature Condition", "Critical"),
        "P0218" to DTCInfo("Transmission Fluid Over Temperature Condition", "Critical"),
        "P0219" to DTCInfo("Engine Overspeed Condition", "Critical"),
        "P0220" to DTCInfo("Throttle/Pedal Position Sensor/Switch B Circuit", "Critical"),
        "P0221" to DTCInfo("Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance", "Critical"),
        "P0222" to DTCInfo("Throttle/Pedal Position Sensor/Switch B Circuit Low Input", "Critical"),
        "P0223" to DTCInfo("Throttle/Pedal Position Sensor/Switch B Circuit High Input", "Critical"),
        "P0224" to DTCInfo("Throttle/Pedal Position Sensor/Switch B Circuit Intermittent", "Critical"),
        "P0225" to DTCInfo("Throttle/Pedal Position Sensor/Switch C Circuit", "Critical"),
        "P0226" to DTCInfo("Throttle/Pedal Position Sensor/Switch C Circuit Range/Performance", "Critical"),
        "P0227" to DTCInfo("Throttle/Pedal Position Sensor/Switch C Circuit Low Input", "Critical"),
        "P0228" to DTCInfo("Throttle/Pedal Position Sensor/Switch C Circuit High Input", "Critical"),
        "P0229" to DTCInfo("Throttle/Pedal Position Sensor/Switch C Circuit Intermittent", "Critical"),
        "P0230" to DTCInfo("Fuel Pump Primary Circuit", "Critical"),
        "P0231" to DTCInfo("Fuel Pump Secondary Circuit Low", "Critical"),
        "P0232" to DTCInfo("Fuel Pump Secondary Circuit High", "Critical"),
        "P0233" to DTCInfo("Fuel Pump Secondary Circuit Intermittent", "Critical"),
        "P0234" to DTCInfo("Turbo/Supercharger Overboost Condition", "Critical"),
        "P0235" to DTCInfo("Turbo/Supercharger Boost Sensor A Circuit", "Important"),
        "P0236" to DTCInfo("Turbo/Supercharger Boost Sensor A Circuit Range/Performance", "Important"),
        "P0237" to DTCInfo("Turbo/Supercharger Boost Sensor A Circuit Low", "Important"),
        "P0238" to DTCInfo("Turbo/Supercharger Boost Sensor A Circuit High", "Important"),
        "P0239" to DTCInfo("Turbo/Supercharger Boost Sensor B Circuit", "Important"),
        "P0240" to DTCInfo("Turbo/Supercharger Boost Sensor B Circuit Range/Performance", "Important"),
        "P0241" to DTCInfo("Turbo/Supercharger Boost Sensor B Circuit Low", "Important"),
        "P0242" to DTCInfo("Turbo/Supercharger Boost Sensor B Circuit High", "Important"),
        "P0243" to DTCInfo("Turbo/Supercharger Wastegate Solenoid A", "Important"),
        "P0244" to DTCInfo("Turbo/Supercharger Wastegate Solenoid A Range/Performance", "Important"),
        "P0245" to DTCInfo("Turbo/Supercharger Wastegate Solenoid A Low", "Important"),
        "P0246" to DTCInfo("Turbo/Supercharger Wastegate Solenoid A High", "Important"),
        "P0247" to DTCInfo("Turbo/Supercharger Wastegate Solenoid B", "Important"),
        "P0248" to DTCInfo("Turbo/Supercharger Wastegate Solenoid B Range/Performance", "Important"),
        "P0249" to DTCInfo("Turbo/Supercharger Wastegate Solenoid B Low", "Important"),
        "P0250" to DTCInfo("Turbo/Supercharger Wastegate Solenoid B High", "Important"),
        "P0251" to DTCInfo("Injection Pump Fuel Metering Control A (Cam/Rotor/Injector)", "Critical"),
        "P0252" to DTCInfo("Injection Pump Fuel Metering Control A Range/Performance", "Critical"),
        "P0253" to DTCInfo("Injection Pump Fuel Metering Control A Low", "Critical"),
        "P0254" to DTCInfo("Injection Pump Fuel Metering Control A High", "Critical"),
        "P0255" to DTCInfo("Injection Pump Fuel Metering Control A Intermittent", "Critical"),
        "P0256" to DTCInfo("Injection Pump Fuel Metering Control B (Cam/Rotor/Injector)", "Critical"),
        "P0257" to DTCInfo("Injection Pump Fuel Metering Control B Range/Performance", "Critical"),
        "P0258" to DTCInfo("Injection Pump Fuel Metering Control B Low", "Critical"),
        "P0259" to DTCInfo("Injection Pump Fuel Metering Control B High", "Critical"),
        "P0260" to DTCInfo("Injection Pump Fuel Metering Control B Intermittent", "Critical"),
        "P0261" to DTCInfo("Cylinder 1 Injector Circuit Low", "Critical"),
        "P0262" to DTCInfo("Cylinder 1 Injector Circuit High", "Critical"),
        "P0263" to DTCInfo("Cylinder 1 Contribution/Balance", "Important"),
        "P0264" to DTCInfo("Cylinder 2 Injector Circuit Low", "Critical"),
        "P0265" to DTCInfo("Cylinder 2 Injector Circuit High", "Critical"),
        "P0266" to DTCInfo("Cylinder 2 Contribution/Balance", "Important"),
        "P0267" to DTCInfo("Cylinder 3 Injector Circuit Low", "Critical"),
        "P0268" to DTCInfo("Cylinder 3 Injector Circuit High", "Critical"),
        "P0269" to DTCInfo("Cylinder 3 Contribution/Balance", "Important"),
        "P0270" to DTCInfo("Cylinder 4 Injector Circuit Low", "Critical"),
        "P0271" to DTCInfo("Cylinder 4 Injector Circuit High", "Critical"),
        "P0272" to DTCInfo("Cylinder 4 Contribution/Balance", "Important"),
        "P0273" to DTCInfo("Cylinder 5 Injector Circuit Low", "Critical"),
        "P0274" to DTCInfo("Cylinder 5 Injector Circuit High", "Critical"),
        "P0275" to DTCInfo("Cylinder 5 Contribution/Balance", "Important"),
        "P0276" to DTCInfo("Cylinder 6 Injector Circuit Low", "Critical"),
        "P0277" to DTCInfo("Cylinder 6 Injector Circuit High", "Critical"),
        "P0278" to DTCInfo("Cylinder 6 Contribution/Balance", "Important"),
        "P0279" to DTCInfo("Cylinder 7 Injector Circuit Low", "Critical"),
        "P0280" to DTCInfo("Cylinder 7 Injector Circuit High", "Critical"),
        "P0281" to DTCInfo("Cylinder 7 Contribution/Balance", "Important"),
        "P0282" to DTCInfo("Cylinder 8 Injector Circuit Low", "Critical"),
        "P0283" to DTCInfo("Cylinder 8 Injector Circuit High", "Critical"),
        "P0284" to DTCInfo("Cylinder 8 Contribution/Balance", "Important"),
        "P0285" to DTCInfo("Cylinder 9 Injector Circuit Low", "Critical"),
        "P0286" to DTCInfo("Cylinder 9 Injector Circuit High", "Critical"),
        "P0287" to DTCInfo("Cylinder 9 Contribution/Balance", "Important"),
        "P0288" to DTCInfo("Cylinder 10 Injector Circuit Low", "Critical"),
        "P0289" to DTCInfo("Cylinder 10 Injector Circuit High", "Critical"),
        "P0290" to DTCInfo("Cylinder 10 Contribution/Balance", "Important"),
        "P0291" to DTCInfo("Cylinder 11 Injector Circuit Low", "Critical"),
        "P0292" to DTCInfo("Cylinder 11 Injector Circuit High", "Critical"),
        "P0293" to DTCInfo("Cylinder 11 Contribution/Balance", "Important"),
        "P0294" to DTCInfo("Cylinder 12 Injector Circuit Low", "Critical"),
        "P0295" to DTCInfo("Cylinder 12 Injector Circuit High", "Critical"),
        "P0296" to DTCInfo("Cylinder 12 Contribution/Balance", "Important"),
        "P0297" to DTCInfo("Vehicle Overspeed Condition", "Critical"),
        "P0298" to DTCInfo("Engine Oil Over Temperature", "Critical"),
        "P0299" to DTCInfo("Turbo/Supercharger Underboost", "Important"),
        
        // P03xx - Ignition System
        "P0300" to DTCInfo("Random/Multiple Cylinder Misfire Detected", "Critical"),
        "P0301" to DTCInfo("Cylinder 1 Misfire Detected", "Critical"),
        "P0302" to DTCInfo("Cylinder 2 Misfire Detected", "Critical"),
        "P0303" to DTCInfo("Cylinder 3 Misfire Detected", "Critical"),
        "P0304" to DTCInfo("Cylinder 4 Misfire Detected", "Critical"),
        "P0305" to DTCInfo("Cylinder 5 Misfire Detected", "Critical"),
        "P0306" to DTCInfo("Cylinder 6 Misfire Detected", "Critical"),
        "P0307" to DTCInfo("Cylinder 7 Misfire Detected", "Critical"),
        "P0308" to DTCInfo("Cylinder 8 Misfire Detected", "Critical"),
        "P0309" to DTCInfo("Cylinder 9 Misfire Detected", "Critical"),
        "P0310" to DTCInfo("Cylinder 10 Misfire Detected", "Critical"),
        "P0311" to DTCInfo("Cylinder 11 Misfire Detected", "Critical"),
        "P0312" to DTCInfo("Cylinder 12 Misfire Detected", "Critical"),
        "P0313" to DTCInfo("Misfire Detected with Low Fuel", "Critical"),
        "P0314" to DTCInfo("Single Cylinder Misfire (Cylinder not Specified)", "Critical"),
        "P0315" to DTCInfo("Crankshaft Position System Variation Not Learned", "Important"),
        "P0316" to DTCInfo("Misfire Detected on Startup (First 1000 Revolutions)", "Important"),
        "P0317" to DTCInfo("Rough Road Hardware Not Present", "Non-Critical"),
        "P0318" to DTCInfo("Rough Road Sensor A Signal Circuit", "Non-Critical"),
        "P0319" to DTCInfo("Rough Road Sensor B Signal Circuit", "Non-Critical"),
        "P0320" to DTCInfo("Ignition/Distributor Engine Speed Input Circuit", "Critical"),
        "P0321" to DTCInfo("Ignition/Distributor Engine Speed Input Circuit Range/Performance", "Critical"),
        "P0322" to DTCInfo("Ignition/Distributor Engine Speed Input Circuit No Signal", "Critical"),
        "P0323" to DTCInfo("Ignition/Distributor Engine Speed Input Circuit Intermittent", "Critical"),
        "P0324" to DTCInfo("Knock Control System Error", "Important"),
        "P0325" to DTCInfo("Knock Sensor 1 Circuit (Bank 1 or Single Sensor)", "Important"),
        "P0326" to DTCInfo("Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)", "Important"),
        "P0327" to DTCInfo("Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)", "Important"),
        "P0328" to DTCInfo("Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)", "Important"),
        "P0329" to DTCInfo("Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)", "Important"),
        "P0330" to DTCInfo("Knock Sensor 2 Circuit (Bank 2)", "Important"),
        "P0331" to DTCInfo("Knock Sensor 2 Circuit Range/Performance (Bank 2)", "Important"),
        "P0332" to DTCInfo("Knock Sensor 2 Circuit Low Input (Bank 2)", "Important"),
        "P0333" to DTCInfo("Knock Sensor 2 Circuit High Input (Bank 2)", "Important"),
        "P0334" to DTCInfo("Knock Sensor 2 Circuit Intermittent (Bank 2)", "Important"),
        "P0335" to DTCInfo("Crankshaft Position Sensor A Circuit", "Critical"),
        "P0336" to DTCInfo("Crankshaft Position Sensor A Circuit Range/Performance", "Critical"),
        "P0337" to DTCInfo("Crankshaft Position Sensor A Circuit Low Input", "Critical"),
        "P0338" to DTCInfo("Crankshaft Position Sensor A Circuit High Input", "Critical"),
        "P0339" to DTCInfo("Crankshaft Position Sensor A Circuit Intermittent", "Critical"),
        "P0340" to DTCInfo("Camshaft Position Sensor A Circuit (Bank 1 or Single Sensor)", "Critical"),
        "P0341" to DTCInfo("Camshaft Position Sensor A Circuit Range/Performance (Bank 1 or Single Sensor)", "Critical"),
        "P0342" to DTCInfo("Camshaft Position Sensor A Circuit Low Input (Bank 1 or Single Sensor)", "Critical"),
        "P0343" to DTCInfo("Camshaft Position Sensor A Circuit High Input (Bank 1 or Single Sensor)", "Critical"),
        "P0344" to DTCInfo("Camshaft Position Sensor A Circuit Intermittent (Bank 1 or Single Sensor)", "Critical"),
        "P0345" to DTCInfo("Camshaft Position Sensor A Circuit (Bank 2)", "Critical"),
        "P0346" to DTCInfo("Camshaft Position Sensor A Circuit Range/Performance (Bank 2)", "Critical"),
        "P0347" to DTCInfo("Camshaft Position Sensor A Circuit Low Input (Bank 2)", "Critical"),
        "P0348" to DTCInfo("Camshaft Position Sensor A Circuit High Input (Bank 2)", "Critical"),
        "P0349" to DTCInfo("Camshaft Position Sensor A Circuit Intermittent (Bank 2)", "Critical"),
        "P0350" to DTCInfo("Ignition Coil Primary/Secondary Circuit", "Critical"),
        "P0351" to DTCInfo("Ignition Coil A Primary/Secondary Circuit", "Critical"),
        "P0352" to DTCInfo("Ignition Coil B Primary/Secondary Circuit", "Critical"),
        "P0353" to DTCInfo("Ignition Coil C Primary/Secondary Circuit", "Critical"),
        "P0354" to DTCInfo("Ignition Coil D Primary/Secondary Circuit", "Critical"),
        "P0355" to DTCInfo("Ignition Coil E Primary/Secondary Circuit", "Critical"),
        "P0356" to DTCInfo("Ignition Coil F Primary/Secondary Circuit", "Critical"),
        "P0357" to DTCInfo("Ignition Coil G Primary/Secondary Circuit", "Critical"),
        "P0358" to DTCInfo("Ignition Coil H Primary/Secondary Circuit", "Critical"),
        "P0359" to DTCInfo("Ignition Coil I Primary/Secondary Circuit", "Critical"),
        "P0360" to DTCInfo("Ignition Coil J Primary/Secondary Circuit", "Critical"),
        "P0361" to DTCInfo("Ignition Coil K Primary/Secondary Circuit", "Critical"),
        "P0362" to DTCInfo("Ignition Coil L Primary/Secondary Circuit", "Critical"),
        "P0363" to DTCInfo("Misfire Detected - Fueling Disabled", "Critical"),
        "P0364" to DTCInfo("Reserved", "Non-Critical"),
        "P0365" to DTCInfo("Camshaft Position Sensor B Circuit (Bank 1)", "Critical"),
        "P0366" to DTCInfo("Camshaft Position Sensor B Circuit Range/Performance (Bank 1)", "Critical"),
        "P0367" to DTCInfo("Camshaft Position Sensor B Circuit Low Input (Bank 1)", "Critical"),
        "P0368" to DTCInfo("Camshaft Position Sensor B Circuit High Input (Bank 1)", "Critical"),
        "P0369" to DTCInfo("Camshaft Position Sensor B Circuit Intermittent (Bank 1)", "Critical"),
        "P0370" to DTCInfo("Timing Reference High Resolution Signal A", "Critical"),
        "P0371" to DTCInfo("Timing Reference High Resolution Signal A Too Many Pulses", "Critical"),
        "P0372" to DTCInfo("Timing Reference High Resolution Signal A Too Few Pulses", "Critical"),
        "P0373" to DTCInfo("Timing Reference High Resolution Signal A Intermittent/Erratic Pulses", "Critical"),
        "P0374" to DTCInfo("Timing Reference High Resolution Signal A No Pulses", "Critical"),
        "P0375" to DTCInfo("Timing Reference High Resolution Signal B", "Critical"),
        "P0376" to DTCInfo("Timing Reference High Resolution Signal B Too Many Pulses", "Critical"),
        "P0377" to DTCInfo("Timing Reference High Resolution Signal B Too Few Pulses", "Critical"),
        "P0378" to DTCInfo("Timing Reference High Resolution Signal B Intermittent/Erratic Pulses", "Critical"),
        "P0379" to DTCInfo("Timing Reference High Resolution Signal B No Pulses", "Critical"),
        "P0380" to DTCInfo("Glow Plug/Heater Circuit A", "Important"),
        "P0381" to DTCInfo("Glow Plug/Heater Indicator Circuit", "Non-Critical"),
        "P0382" to DTCInfo("Glow Plug/Heater Circuit B", "Important"),
        "P0383" to DTCInfo("Glow Plug Control Module Control Circuit Low", "Important"),
        "P0384" to DTCInfo("Glow Plug Control Module Control Circuit High", "Important"),
        "P0385" to DTCInfo("Crankshaft Position Sensor B Circuit", "Critical"),
        "P0386" to DTCInfo("Crankshaft Position Sensor B Circuit Range/Performance", "Critical"),
        "P0387" to DTCInfo("Crankshaft Position Sensor B Circuit Low Input", "Critical"),
        "P0388" to DTCInfo("Crankshaft Position Sensor B Circuit High Input", "Critical"),
        "P0389" to DTCInfo("Crankshaft Position Sensor B Circuit Intermittent", "Critical"),
        "P0390" to DTCInfo("Camshaft Position Sensor B Circuit (Bank 2)", "Critical"),
        "P0391" to DTCInfo("Camshaft Position Sensor B Circuit Range/Performance (Bank 2)", "Critical"),
        "P0392" to DTCInfo("Camshaft Position Sensor B Circuit Low Input (Bank 2)", "Critical"),
        "P0393" to DTCInfo("Camshaft Position Sensor B Circuit High Input (Bank 2)", "Critical"),
        "P0394" to DTCInfo("Camshaft Position Sensor B Circuit Intermittent (Bank 2)", "Critical")
    )
}
